# encoding: utf-8
#
# This file is machine generated.  DO NOT EDIT!
#
if Kernel.respond_to?(:require_relative)
  require_relative("./helper")
else
  $:.unshift(File.dirname(__FILE__))
  require 'helper'
end
#
# == Purpose
#
# Tests for the #{UTF8::Validator} implementation.
#
# Test data pulled and generated from:
#
# https://www.unicode.org/Public/10.0.0/ucd/
#
class TestUnicode10SpecialCasing < Test::Unit::TestCase
  #
  def setup
    @validator = UTF8::Validator.new
    @vercheck = ((RUBY_VERSION =~ /1.9/) or (RUBY_VERSION =~ /2./)) ? true : false
  end

  #
  def teardown
    @validator = nil
  end

  def test_unicode10_SpecialCasing
    test_data = [
      "\d00DF",  # LATIN SMALL LETTER SHARP S
      "\d00DF",  # LATIN SMALL LETTER SHARP S
      "\d0053",  # LATIN SMALL LETTER SHARP S
      "\d0073",  # LATIN SMALL LETTER SHARP S
      "\d0053",  # LATIN SMALL LETTER SHARP S
      "\d0053",  # LATIN SMALL LETTER SHARP S
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0069",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0307",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\dFB00",  # LATIN SMALL LIGATURE FF
      "\dFB00",  # LATIN SMALL LIGATURE FF
      "\d0046",  # LATIN SMALL LIGATURE FF
      "\d0066",  # LATIN SMALL LIGATURE FF
      "\d0046",  # LATIN SMALL LIGATURE FF
      "\d0046",  # LATIN SMALL LIGATURE FF
      "\dFB01",  # LATIN SMALL LIGATURE FI
      "\dFB01",  # LATIN SMALL LIGATURE FI
      "\d0046",  # LATIN SMALL LIGATURE FI
      "\d0069",  # LATIN SMALL LIGATURE FI
      "\d0046",  # LATIN SMALL LIGATURE FI
      "\d0049",  # LATIN SMALL LIGATURE FI
      "\dFB02",  # LATIN SMALL LIGATURE FL
      "\dFB02",  # LATIN SMALL LIGATURE FL
      "\d0046",  # LATIN SMALL LIGATURE FL
      "\d006C",  # LATIN SMALL LIGATURE FL
      "\d0046",  # LATIN SMALL LIGATURE FL
      "\d004C",  # LATIN SMALL LIGATURE FL
      "\dFB03",  # LATIN SMALL LIGATURE FFI
      "\dFB03",  # LATIN SMALL LIGATURE FFI
      "\d0046",  # LATIN SMALL LIGATURE FFI
      "\d0066",  # LATIN SMALL LIGATURE FFI
      "\d0069",  # LATIN SMALL LIGATURE FFI
      "\d0046",  # LATIN SMALL LIGATURE FFI
      "\d0046",  # LATIN SMALL LIGATURE FFI
      "\d0049",  # LATIN SMALL LIGATURE FFI
      "\dFB04",  # LATIN SMALL LIGATURE FFL
      "\dFB04",  # LATIN SMALL LIGATURE FFL
      "\d0046",  # LATIN SMALL LIGATURE FFL
      "\d0066",  # LATIN SMALL LIGATURE FFL
      "\d006C",  # LATIN SMALL LIGATURE FFL
      "\d0046",  # LATIN SMALL LIGATURE FFL
      "\d0046",  # LATIN SMALL LIGATURE FFL
      "\d004C",  # LATIN SMALL LIGATURE FFL
      "\dFB05",  # LATIN SMALL LIGATURE LONG S T
      "\dFB05",  # LATIN SMALL LIGATURE LONG S T
      "\d0053",  # LATIN SMALL LIGATURE LONG S T
      "\d0074",  # LATIN SMALL LIGATURE LONG S T
      "\d0053",  # LATIN SMALL LIGATURE LONG S T
      "\d0054",  # LATIN SMALL LIGATURE LONG S T
      "\dFB06",  # LATIN SMALL LIGATURE ST
      "\dFB06",  # LATIN SMALL LIGATURE ST
      "\d0053",  # LATIN SMALL LIGATURE ST
      "\d0074",  # LATIN SMALL LIGATURE ST
      "\d0053",  # LATIN SMALL LIGATURE ST
      "\d0054",  # LATIN SMALL LIGATURE ST
      "\d0587",  # ARMENIAN SMALL LIGATURE ECH YIWN
      "\d0587",  # ARMENIAN SMALL LIGATURE ECH YIWN
      "\d0535",  # ARMENIAN SMALL LIGATURE ECH YIWN
      "\d0582",  # ARMENIAN SMALL LIGATURE ECH YIWN
      "\d0535",  # ARMENIAN SMALL LIGATURE ECH YIWN
      "\d0552",  # ARMENIAN SMALL LIGATURE ECH YIWN
      "\dFB13",  # ARMENIAN SMALL LIGATURE MEN NOW
      "\dFB13",  # ARMENIAN SMALL LIGATURE MEN NOW
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN NOW
      "\d0576",  # ARMENIAN SMALL LIGATURE MEN NOW
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN NOW
      "\d0546",  # ARMENIAN SMALL LIGATURE MEN NOW
      "\dFB14",  # ARMENIAN SMALL LIGATURE MEN ECH
      "\dFB14",  # ARMENIAN SMALL LIGATURE MEN ECH
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN ECH
      "\d0565",  # ARMENIAN SMALL LIGATURE MEN ECH
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN ECH
      "\d0535",  # ARMENIAN SMALL LIGATURE MEN ECH
      "\dFB15",  # ARMENIAN SMALL LIGATURE MEN INI
      "\dFB15",  # ARMENIAN SMALL LIGATURE MEN INI
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN INI
      "\d056B",  # ARMENIAN SMALL LIGATURE MEN INI
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN INI
      "\d053B",  # ARMENIAN SMALL LIGATURE MEN INI
      "\dFB16",  # ARMENIAN SMALL LIGATURE VEW NOW
      "\dFB16",  # ARMENIAN SMALL LIGATURE VEW NOW
      "\d054E",  # ARMENIAN SMALL LIGATURE VEW NOW
      "\d0576",  # ARMENIAN SMALL LIGATURE VEW NOW
      "\d054E",  # ARMENIAN SMALL LIGATURE VEW NOW
      "\d0546",  # ARMENIAN SMALL LIGATURE VEW NOW
      "\dFB17",  # ARMENIAN SMALL LIGATURE MEN XEH
      "\dFB17",  # ARMENIAN SMALL LIGATURE MEN XEH
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN XEH
      "\d056D",  # ARMENIAN SMALL LIGATURE MEN XEH
      "\d0544",  # ARMENIAN SMALL LIGATURE MEN XEH
      "\d053D",  # ARMENIAN SMALL LIGATURE MEN XEH
      "\d0149",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
      "\d0149",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
      "\d02BC",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
      "\d004E",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
      "\d02BC",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
      "\d004E",  # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
      "\d0390",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0390",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0301",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d0301",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
      "\d03B0",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d03B0",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d0301",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d0301",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
      "\d01F0",  # LATIN SMALL LETTER J WITH CARON
      "\d01F0",  # LATIN SMALL LETTER J WITH CARON
      "\d004A",  # LATIN SMALL LETTER J WITH CARON
      "\d030C",  # LATIN SMALL LETTER J WITH CARON
      "\d004A",  # LATIN SMALL LETTER J WITH CARON
      "\d030C",  # LATIN SMALL LETTER J WITH CARON
      "\d1E96",  # LATIN SMALL LETTER H WITH LINE BELOW
      "\d1E96",  # LATIN SMALL LETTER H WITH LINE BELOW
      "\d0048",  # LATIN SMALL LETTER H WITH LINE BELOW
      "\d0331",  # LATIN SMALL LETTER H WITH LINE BELOW
      "\d0048",  # LATIN SMALL LETTER H WITH LINE BELOW
      "\d0331",  # LATIN SMALL LETTER H WITH LINE BELOW
      "\d1E97",  # LATIN SMALL LETTER T WITH DIAERESIS
      "\d1E97",  # LATIN SMALL LETTER T WITH DIAERESIS
      "\d0054",  # LATIN SMALL LETTER T WITH DIAERESIS
      "\d0308",  # LATIN SMALL LETTER T WITH DIAERESIS
      "\d0054",  # LATIN SMALL LETTER T WITH DIAERESIS
      "\d0308",  # LATIN SMALL LETTER T WITH DIAERESIS
      "\d1E98",  # LATIN SMALL LETTER W WITH RING ABOVE
      "\d1E98",  # LATIN SMALL LETTER W WITH RING ABOVE
      "\d0057",  # LATIN SMALL LETTER W WITH RING ABOVE
      "\d030A",  # LATIN SMALL LETTER W WITH RING ABOVE
      "\d0057",  # LATIN SMALL LETTER W WITH RING ABOVE
      "\d030A",  # LATIN SMALL LETTER W WITH RING ABOVE
      "\d1E99",  # LATIN SMALL LETTER Y WITH RING ABOVE
      "\d1E99",  # LATIN SMALL LETTER Y WITH RING ABOVE
      "\d0059",  # LATIN SMALL LETTER Y WITH RING ABOVE
      "\d030A",  # LATIN SMALL LETTER Y WITH RING ABOVE
      "\d0059",  # LATIN SMALL LETTER Y WITH RING ABOVE
      "\d030A",  # LATIN SMALL LETTER Y WITH RING ABOVE
      "\d1E9A",  # LATIN SMALL LETTER A WITH RIGHT HALF RING
      "\d1E9A",  # LATIN SMALL LETTER A WITH RIGHT HALF RING
      "\d0041",  # LATIN SMALL LETTER A WITH RIGHT HALF RING
      "\d02BE",  # LATIN SMALL LETTER A WITH RIGHT HALF RING
      "\d0041",  # LATIN SMALL LETTER A WITH RIGHT HALF RING
      "\d02BE",  # LATIN SMALL LETTER A WITH RIGHT HALF RING
      "\d1F50",  # GREEK SMALL LETTER UPSILON WITH PSILI
      "\d1F50",  # GREEK SMALL LETTER UPSILON WITH PSILI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI
      "\d1F52",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d1F52",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d0300",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d0300",  # GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
      "\d1F54",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d1F54",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d0301",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d0301",  # GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
      "\d1F56",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d1F56",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d0313",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
      "\d1FB6",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
      "\d1FB6",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
      "\d0391",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
      "\d0391",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI
      "\d1FC6",  # GREEK SMALL LETTER ETA WITH PERISPOMENI
      "\d1FC6",  # GREEK SMALL LETTER ETA WITH PERISPOMENI
      "\d0397",  # GREEK SMALL LETTER ETA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER ETA WITH PERISPOMENI
      "\d0397",  # GREEK SMALL LETTER ETA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER ETA WITH PERISPOMENI
      "\d1FD2",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d1FD2",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d0300",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d0300",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
      "\d1FD3",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d1FD3",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d0301",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d0301",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
      "\d1FD6",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI
      "\d1FD6",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI
      "\d0399",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI
      "\d0399",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER IOTA WITH PERISPOMENI
      "\d1FD7",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d1FD7",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d0399",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d0308",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
      "\d1FE2",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d1FE2",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d0300",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d0300",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
      "\d1FE3",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d1FE3",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d0301",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d0301",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
      "\d1FE4",  # GREEK SMALL LETTER RHO WITH PSILI
      "\d1FE4",  # GREEK SMALL LETTER RHO WITH PSILI
      "\d03A1",  # GREEK SMALL LETTER RHO WITH PSILI
      "\d0313",  # GREEK SMALL LETTER RHO WITH PSILI
      "\d03A1",  # GREEK SMALL LETTER RHO WITH PSILI
      "\d0313",  # GREEK SMALL LETTER RHO WITH PSILI
      "\d1FE6",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
      "\d1FE6",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER UPSILON WITH PERISPOMENI
      "\d1FE7",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d1FE7",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d03A5",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d0308",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
      "\d1FF6",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
      "\d1FF6",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
      "\d03A9",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
      "\d03A9",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
      "\d0342",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI
      "\d1F80",  # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
      "\d1F80",  # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
      "\d1F88",  # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
      "\d1F08",  # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
      "\d1F81",  # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
      "\d1F81",  # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
      "\d1F89",  # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
      "\d1F09",  # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
      "\d1F82",  # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F82",  # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F8A",  # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F0A",  # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F83",  # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F83",  # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F8B",  # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F0B",  # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F84",  # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F84",  # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F8C",  # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F0C",  # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F85",  # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F85",  # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F8D",  # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F0D",  # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F86",  # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F86",  # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F8E",  # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F0E",  # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F87",  # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F87",  # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F8F",  # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F0F",  # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F88",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
      "\d1F80",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
      "\d1F88",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
      "\d1F08",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
      "\d1F89",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
      "\d1F81",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
      "\d1F89",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
      "\d1F09",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
      "\d1F8A",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F82",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F8A",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F0A",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F8B",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F83",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F8B",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F0B",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F8C",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F84",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F8C",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F0C",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F8D",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F85",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F8D",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F0D",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F8E",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F86",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F8E",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F0E",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F8F",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F87",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F8F",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F0F",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F90",  # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
      "\d1F90",  # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
      "\d1F98",  # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
      "\d1F28",  # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
      "\d1F91",  # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
      "\d1F91",  # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
      "\d1F99",  # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
      "\d1F29",  # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
      "\d1F92",  # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F92",  # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F9A",  # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F2A",  # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F93",  # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F93",  # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F9B",  # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F2B",  # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F94",  # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F94",  # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F9C",  # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F2C",  # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F95",  # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F95",  # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F9D",  # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F2D",  # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F96",  # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F96",  # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F9E",  # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F2E",  # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F97",  # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F97",  # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F9F",  # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F2F",  # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F98",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
      "\d1F90",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
      "\d1F98",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
      "\d1F28",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
      "\d1F99",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
      "\d1F91",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
      "\d1F99",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
      "\d1F29",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
      "\d1F9A",  # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F92",  # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F9A",  # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F2A",  # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F9B",  # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F93",  # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F9B",  # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F2B",  # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F9C",  # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F94",  # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F9C",  # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F2C",  # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F9D",  # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F95",  # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F9D",  # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F2D",  # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F9E",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F96",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F9E",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F2E",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F9F",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F97",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F9F",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F2F",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FA0",  # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
      "\d1FA0",  # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
      "\d1FA8",  # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
      "\d1F68",  # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
      "\d1FA1",  # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
      "\d1FA1",  # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
      "\d1FA9",  # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
      "\d1F69",  # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
      "\d1FA2",  # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1FA2",  # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1FAA",  # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1F6A",  # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
      "\d1FA3",  # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1FA3",  # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1FAB",  # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1F6B",  # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
      "\d1FA4",  # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1FA4",  # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1FAC",  # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1F6C",  # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
      "\d1FA5",  # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1FA5",  # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1FAD",  # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1F6D",  # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
      "\d1FA6",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1FA6",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1FAE",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F6E",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1FA7",  # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1FA7",  # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1FAF",  # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1F6F",  # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
      "\d1FA8",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
      "\d1FA0",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
      "\d1FA8",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
      "\d1F68",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
      "\d1FA9",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
      "\d1FA1",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
      "\d1FA9",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
      "\d1F69",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
      "\d1FAA",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1FA2",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1FAA",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1F6A",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
      "\d1FAB",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1FA3",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1FAB",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1F6B",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
      "\d1FAC",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1FA4",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1FAC",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1F6C",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
      "\d1FAD",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1FA5",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1FAD",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1F6D",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
      "\d1FAE",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FA6",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FAE",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F6E",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FAF",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FA7",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FAF",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1F6F",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
      "\d1FB3",  # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
      "\d1FB3",  # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
      "\d1FBC",  # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
      "\d0391",  # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
      "\d1FBC",  # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
      "\d1FB3",  # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
      "\d1FBC",  # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
      "\d0391",  # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
      "\d1FC3",  # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
      "\d1FC3",  # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
      "\d1FCC",  # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
      "\d0397",  # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
      "\d1FCC",  # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
      "\d1FC3",  # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
      "\d1FCC",  # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
      "\d0397",  # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
      "\d1FF3",  # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
      "\d1FF3",  # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
      "\d1FFC",  # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
      "\d03A9",  # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
      "\d1FFC",  # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
      "\d1FF3",  # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
      "\d1FFC",  # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
      "\d03A9",  # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
      "\d0399",  # GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
      "\d1FB2",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
      "\d1FB2",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
      "\d1FBA",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
      "\d1FBA",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
      "\d1FB4",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
      "\d1FB4",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
      "\d0386",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
      "\d0386",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
      "\d1FC2",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
      "\d1FC2",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
      "\d1FCA",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
      "\d1FCA",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
      "\d1FC4",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
      "\d1FC4",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
      "\d0389",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
      "\d0389",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
      "\d1FF2",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
      "\d1FF2",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
      "\d1FFA",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
      "\d1FFA",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
      "\d1FF4",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
      "\d1FF4",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
      "\d038F",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
      "\d038F",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
      "\d1FB7",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d1FB7",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0391",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0342",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0391",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0342",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d1FC7",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d1FC7",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0397",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0342",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0397",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0342",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d1FF7",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d1FF7",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d03A9",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0342",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0345",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d03A9",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0342",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d0399",  # GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
      "\d03A3",  # GREEK CAPITAL LETTER SIGMA
      "\d03C2",  # GREEK CAPITAL LETTER SIGMA
      "\d03A3",  # GREEK CAPITAL LETTER SIGMA
      "\d03A3",  # GREEK CAPITAL LETTER SIGMA
      "\dFinal_Sigma",  # GREEK CAPITAL LETTER SIGMA
      "\d0307",  # COMBINING DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\dlt",  # COMBINING DOT ABOVE
      "\dAfter_Soft_Dotted",  # COMBINING DOT ABOVE
      "\d0049",  # LATIN CAPITAL LETTER I
      "\d0069",  # LATIN CAPITAL LETTER I
      "\d0307",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\dlt",  # LATIN CAPITAL LETTER I
      "\dMore_Above",  # LATIN CAPITAL LETTER I
      "\d004A",  # LATIN CAPITAL LETTER J
      "\d006A",  # LATIN CAPITAL LETTER J
      "\d0307",  # LATIN CAPITAL LETTER J
      "\d004A",  # LATIN CAPITAL LETTER J
      "\d004A",  # LATIN CAPITAL LETTER J
      "\dlt",  # LATIN CAPITAL LETTER J
      "\dMore_Above",  # LATIN CAPITAL LETTER J
      "\d012E",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\d012F",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\d0307",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\d012E",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\d012E",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\dlt",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\dMore_Above",  # LATIN CAPITAL LETTER I WITH OGONEK
      "\d00CC",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\d0069",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\d0307",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\d0300",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\d00CC",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\d00CC",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\dlt",  # LATIN CAPITAL LETTER I WITH GRAVE
      "\d00CD",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\d0069",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\d0307",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\d0301",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\d00CD",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\d00CD",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\dlt",  # LATIN CAPITAL LETTER I WITH ACUTE
      "\d0128",  # LATIN CAPITAL LETTER I WITH TILDE
      "\d0069",  # LATIN CAPITAL LETTER I WITH TILDE
      "\d0307",  # LATIN CAPITAL LETTER I WITH TILDE
      "\d0303",  # LATIN CAPITAL LETTER I WITH TILDE
      "\d0128",  # LATIN CAPITAL LETTER I WITH TILDE
      "\d0128",  # LATIN CAPITAL LETTER I WITH TILDE
      "\dlt",  # LATIN CAPITAL LETTER I WITH TILDE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0069",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\dtr",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0069",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0130",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\daz",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\dtr",  # COMBINING DOT ABOVE
      "\dAfter_I",  # COMBINING DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\d0307",  # COMBINING DOT ABOVE
      "\daz",  # COMBINING DOT ABOVE
      "\dAfter_I",  # COMBINING DOT ABOVE
      "\d0049",  # LATIN CAPITAL LETTER I
      "\d0131",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\dtr",  # LATIN CAPITAL LETTER I
      "\dNot_Before_Dot",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\d0131",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\d0049",  # LATIN CAPITAL LETTER I
      "\daz",  # LATIN CAPITAL LETTER I
      "\dNot_Before_Dot",  # LATIN CAPITAL LETTER I
      "\d0069",  # LATIN SMALL LETTER I
      "\d0069",  # LATIN SMALL LETTER I
      "\d0130",  # LATIN SMALL LETTER I
      "\d0130",  # LATIN SMALL LETTER I
      "\dtr",  # LATIN SMALL LETTER I
      "\d0069",  # LATIN SMALL LETTER I
      "\d0069",  # LATIN SMALL LETTER I
      "\d0130",  # LATIN SMALL LETTER I
      "\d0130",  # LATIN SMALL LETTER I
      "\daz",  # LATIN SMALL LETTER I
    ]
    test_data.each do |string|
      assert @validator.valid_encoding?(string), "U10_SpecialCasing: #{string}"
      assert string.force_encoding("UTF-8").valid_encoding?, "U10_SpecialCasing: #{string}" if @vercheck
    end
  end

end
