# encoding: utf-8
#
# This file is machine generated.  DO NOT EDIT!
#
if Kernel.respond_to?(:require_relative)
  require_relative("./helper")
else
  $:.unshift(File.dirname(__FILE__))
  require 'helper'
end
#
# == Purpose
#
# Tests for the #{UTF8::Validator} implementation.
#
# Test data pulled and generated from:
#
# https://www.unicode.org/Public/10.0.0/ucd/
#
class TestUnicode10BidiBrackets < Test::Unit::TestCase
  #
  def setup
    @validator = UTF8::Validator.new
    @vercheck = ((RUBY_VERSION =~ /1.9/) or (RUBY_VERSION =~ /2./)) ? true : false
  end

  #
  def teardown
    @validator = nil
  end

  def test_unicode10_BidiBrackets
    test_data = [
        "\d0028",  # LEFT PARENTHESIS
        "\d0029",  # LEFT PARENTHESIS
        "\d0029",  # RIGHT PARENTHESIS
        "\d0028",  # RIGHT PARENTHESIS
        "\d005B",  # LEFT SQUARE BRACKET
        "\d005D",  # LEFT SQUARE BRACKET
        "\d005D",  # RIGHT SQUARE BRACKET
        "\d005B",  # RIGHT SQUARE BRACKET
        "\d007B",  # LEFT CURLY BRACKET
        "\d007D",  # LEFT CURLY BRACKET
        "\d007D",  # RIGHT CURLY BRACKET
        "\d007B",  # RIGHT CURLY BRACKET
        "\d0F3A",  # TIBETAN MARK GUG RTAGS GYON
        "\d0F3B",  # TIBETAN MARK GUG RTAGS GYON
        "\d0F3B",  # TIBETAN MARK GUG RTAGS GYAS
        "\d0F3A",  # TIBETAN MARK GUG RTAGS GYAS
        "\d0F3C",  # TIBETAN MARK ANG KHANG GYON
        "\d0F3D",  # TIBETAN MARK ANG KHANG GYON
        "\d0F3D",  # TIBETAN MARK ANG KHANG GYAS
        "\d0F3C",  # TIBETAN MARK ANG KHANG GYAS
        "\d169B",  # OGHAM FEATHER MARK
        "\d169C",  # OGHAM FEATHER MARK
        "\d169C",  # OGHAM REVERSED FEATHER MARK
        "\d169B",  # OGHAM REVERSED FEATHER MARK
        "\d2045",  # LEFT SQUARE BRACKET WITH QUILL
        "\d2046",  # LEFT SQUARE BRACKET WITH QUILL
        "\d2046",  # RIGHT SQUARE BRACKET WITH QUILL
        "\d2045",  # RIGHT SQUARE BRACKET WITH QUILL
        "\d207D",  # SUPERSCRIPT LEFT PARENTHESIS
        "\d207E",  # SUPERSCRIPT LEFT PARENTHESIS
        "\d207E",  # SUPERSCRIPT RIGHT PARENTHESIS
        "\d207D",  # SUPERSCRIPT RIGHT PARENTHESIS
        "\d208D",  # SUBSCRIPT LEFT PARENTHESIS
        "\d208E",  # SUBSCRIPT LEFT PARENTHESIS
        "\d208E",  # SUBSCRIPT RIGHT PARENTHESIS
        "\d208D",  # SUBSCRIPT RIGHT PARENTHESIS
        "\d2308",  # LEFT CEILING
        "\d2309",  # LEFT CEILING
        "\d2309",  # RIGHT CEILING
        "\d2308",  # RIGHT CEILING
        "\d230A",  # LEFT FLOOR
        "\d230B",  # LEFT FLOOR
        "\d230B",  # RIGHT FLOOR
        "\d230A",  # RIGHT FLOOR
        "\d2329",  # LEFT-POINTING ANGLE BRACKET
        "\d232A",  # LEFT-POINTING ANGLE BRACKET
        "\d232A",  # RIGHT-POINTING ANGLE BRACKET
        "\d2329",  # RIGHT-POINTING ANGLE BRACKET
        "\d2768",  # MEDIUM LEFT PARENTHESIS ORNAMENT
        "\d2769",  # MEDIUM LEFT PARENTHESIS ORNAMENT
        "\d2769",  # MEDIUM RIGHT PARENTHESIS ORNAMENT
        "\d2768",  # MEDIUM RIGHT PARENTHESIS ORNAMENT
        "\d276A",  # MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
        "\d276B",  # MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
        "\d276B",  # MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
        "\d276A",  # MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
        "\d276C",  # MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
        "\d276D",  # MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
        "\d276D",  # MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
        "\d276C",  # MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
        "\d276E",  # HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
        "\d276F",  # HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
        "\d276F",  # HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
        "\d276E",  # HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
        "\d2770",  # HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
        "\d2771",  # HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
        "\d2771",  # HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
        "\d2770",  # HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
        "\d2772",  # LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT
        "\d2773",  # LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT
        "\d2773",  # LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
        "\d2772",  # LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
        "\d2774",  # MEDIUM LEFT CURLY BRACKET ORNAMENT
        "\d2775",  # MEDIUM LEFT CURLY BRACKET ORNAMENT
        "\d2775",  # MEDIUM RIGHT CURLY BRACKET ORNAMENT
        "\d2774",  # MEDIUM RIGHT CURLY BRACKET ORNAMENT
        "\d27C5",  # LEFT S-SHAPED BAG DELIMITER
        "\d27C6",  # LEFT S-SHAPED BAG DELIMITER
        "\d27C6",  # RIGHT S-SHAPED BAG DELIMITER
        "\d27C5",  # RIGHT S-SHAPED BAG DELIMITER
        "\d27E6",  # MATHEMATICAL LEFT WHITE SQUARE BRACKET
        "\d27E7",  # MATHEMATICAL LEFT WHITE SQUARE BRACKET
        "\d27E7",  # MATHEMATICAL RIGHT WHITE SQUARE BRACKET
        "\d27E6",  # MATHEMATICAL RIGHT WHITE SQUARE BRACKET
        "\d27E8",  # MATHEMATICAL LEFT ANGLE BRACKET
        "\d27E9",  # MATHEMATICAL LEFT ANGLE BRACKET
        "\d27E9",  # MATHEMATICAL RIGHT ANGLE BRACKET
        "\d27E8",  # MATHEMATICAL RIGHT ANGLE BRACKET
        "\d27EA",  # MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
        "\d27EB",  # MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
        "\d27EB",  # MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
        "\d27EA",  # MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
        "\d27EC",  # MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
        "\d27ED",  # MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
        "\d27ED",  # MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
        "\d27EC",  # MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
        "\d27EE",  # MATHEMATICAL LEFT FLATTENED PARENTHESIS
        "\d27EF",  # MATHEMATICAL LEFT FLATTENED PARENTHESIS
        "\d27EF",  # MATHEMATICAL RIGHT FLATTENED PARENTHESIS
        "\d27EE",  # MATHEMATICAL RIGHT FLATTENED PARENTHESIS
        "\d2983",  # LEFT WHITE CURLY BRACKET
        "\d2984",  # LEFT WHITE CURLY BRACKET
        "\d2984",  # RIGHT WHITE CURLY BRACKET
        "\d2983",  # RIGHT WHITE CURLY BRACKET
        "\d2985",  # LEFT WHITE PARENTHESIS
        "\d2986",  # LEFT WHITE PARENTHESIS
        "\d2986",  # RIGHT WHITE PARENTHESIS
        "\d2985",  # RIGHT WHITE PARENTHESIS
        "\d2987",  # Z NOTATION LEFT IMAGE BRACKET
        "\d2988",  # Z NOTATION LEFT IMAGE BRACKET
        "\d2988",  # Z NOTATION RIGHT IMAGE BRACKET
        "\d2987",  # Z NOTATION RIGHT IMAGE BRACKET
        "\d2989",  # Z NOTATION LEFT BINDING BRACKET
        "\d298A",  # Z NOTATION LEFT BINDING BRACKET
        "\d298A",  # Z NOTATION RIGHT BINDING BRACKET
        "\d2989",  # Z NOTATION RIGHT BINDING BRACKET
        "\d298B",  # LEFT SQUARE BRACKET WITH UNDERBAR
        "\d298C",  # LEFT SQUARE BRACKET WITH UNDERBAR
        "\d298C",  # RIGHT SQUARE BRACKET WITH UNDERBAR
        "\d298B",  # RIGHT SQUARE BRACKET WITH UNDERBAR
        "\d298D",  # LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
        "\d2990",  # LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
        "\d298E",  # RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
        "\d298F",  # RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
        "\d298F",  # LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
        "\d298E",  # LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
        "\d2990",  # RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
        "\d298D",  # RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
        "\d2991",  # LEFT ANGLE BRACKET WITH DOT
        "\d2992",  # LEFT ANGLE BRACKET WITH DOT
        "\d2992",  # RIGHT ANGLE BRACKET WITH DOT
        "\d2991",  # RIGHT ANGLE BRACKET WITH DOT
        "\d2993",  # LEFT ARC LESS-THAN BRACKET
        "\d2994",  # LEFT ARC LESS-THAN BRACKET
        "\d2994",  # RIGHT ARC GREATER-THAN BRACKET
        "\d2993",  # RIGHT ARC GREATER-THAN BRACKET
        "\d2995",  # DOUBLE LEFT ARC GREATER-THAN BRACKET
        "\d2996",  # DOUBLE LEFT ARC GREATER-THAN BRACKET
        "\d2996",  # DOUBLE RIGHT ARC LESS-THAN BRACKET
        "\d2995",  # DOUBLE RIGHT ARC LESS-THAN BRACKET
        "\d2997",  # LEFT BLACK TORTOISE SHELL BRACKET
        "\d2998",  # LEFT BLACK TORTOISE SHELL BRACKET
        "\d2998",  # RIGHT BLACK TORTOISE SHELL BRACKET
        "\d2997",  # RIGHT BLACK TORTOISE SHELL BRACKET
        "\d29D8",  # LEFT WIGGLY FENCE
        "\d29D9",  # LEFT WIGGLY FENCE
        "\d29D9",  # RIGHT WIGGLY FENCE
        "\d29D8",  # RIGHT WIGGLY FENCE
        "\d29DA",  # LEFT DOUBLE WIGGLY FENCE
        "\d29DB",  # LEFT DOUBLE WIGGLY FENCE
        "\d29DB",  # RIGHT DOUBLE WIGGLY FENCE
        "\d29DA",  # RIGHT DOUBLE WIGGLY FENCE
        "\d29FC",  # LEFT-POINTING CURVED ANGLE BRACKET
        "\d29FD",  # LEFT-POINTING CURVED ANGLE BRACKET
        "\d29FD",  # RIGHT-POINTING CURVED ANGLE BRACKET
        "\d29FC",  # RIGHT-POINTING CURVED ANGLE BRACKET
        "\d2E22",  # TOP LEFT HALF BRACKET
        "\d2E23",  # TOP LEFT HALF BRACKET
        "\d2E23",  # TOP RIGHT HALF BRACKET
        "\d2E22",  # TOP RIGHT HALF BRACKET
        "\d2E24",  # BOTTOM LEFT HALF BRACKET
        "\d2E25",  # BOTTOM LEFT HALF BRACKET
        "\d2E25",  # BOTTOM RIGHT HALF BRACKET
        "\d2E24",  # BOTTOM RIGHT HALF BRACKET
        "\d2E26",  # LEFT SIDEWAYS U BRACKET
        "\d2E27",  # LEFT SIDEWAYS U BRACKET
        "\d2E27",  # RIGHT SIDEWAYS U BRACKET
        "\d2E26",  # RIGHT SIDEWAYS U BRACKET
        "\d2E28",  # LEFT DOUBLE PARENTHESIS
        "\d2E29",  # LEFT DOUBLE PARENTHESIS
        "\d2E29",  # RIGHT DOUBLE PARENTHESIS
        "\d2E28",  # RIGHT DOUBLE PARENTHESIS
        "\d3008",  # LEFT ANGLE BRACKET
        "\d3009",  # LEFT ANGLE BRACKET
        "\d3009",  # RIGHT ANGLE BRACKET
        "\d3008",  # RIGHT ANGLE BRACKET
        "\d300A",  # LEFT DOUBLE ANGLE BRACKET
        "\d300B",  # LEFT DOUBLE ANGLE BRACKET
        "\d300B",  # RIGHT DOUBLE ANGLE BRACKET
        "\d300A",  # RIGHT DOUBLE ANGLE BRACKET
        "\d300C",  # LEFT CORNER BRACKET
        "\d300D",  # LEFT CORNER BRACKET
        "\d300D",  # RIGHT CORNER BRACKET
        "\d300C",  # RIGHT CORNER BRACKET
        "\d300E",  # LEFT WHITE CORNER BRACKET
        "\d300F",  # LEFT WHITE CORNER BRACKET
        "\d300F",  # RIGHT WHITE CORNER BRACKET
        "\d300E",  # RIGHT WHITE CORNER BRACKET
        "\d3010",  # LEFT BLACK LENTICULAR BRACKET
        "\d3011",  # LEFT BLACK LENTICULAR BRACKET
        "\d3011",  # RIGHT BLACK LENTICULAR BRACKET
        "\d3010",  # RIGHT BLACK LENTICULAR BRACKET
        "\d3014",  # LEFT TORTOISE SHELL BRACKET
        "\d3015",  # LEFT TORTOISE SHELL BRACKET
        "\d3015",  # RIGHT TORTOISE SHELL BRACKET
        "\d3014",  # RIGHT TORTOISE SHELL BRACKET
        "\d3016",  # LEFT WHITE LENTICULAR BRACKET
        "\d3017",  # LEFT WHITE LENTICULAR BRACKET
        "\d3017",  # RIGHT WHITE LENTICULAR BRACKET
        "\d3016",  # RIGHT WHITE LENTICULAR BRACKET
        "\d3018",  # LEFT WHITE TORTOISE SHELL BRACKET
        "\d3019",  # LEFT WHITE TORTOISE SHELL BRACKET
        "\d3019",  # RIGHT WHITE TORTOISE SHELL BRACKET
        "\d3018",  # RIGHT WHITE TORTOISE SHELL BRACKET
        "\d301A",  # LEFT WHITE SQUARE BRACKET
        "\d301B",  # LEFT WHITE SQUARE BRACKET
        "\d301B",  # RIGHT WHITE SQUARE BRACKET
        "\d301A",  # RIGHT WHITE SQUARE BRACKET
        "\dFE59",  # SMALL LEFT PARENTHESIS
        "\dFE5A",  # SMALL LEFT PARENTHESIS
        "\dFE5A",  # SMALL RIGHT PARENTHESIS
        "\dFE59",  # SMALL RIGHT PARENTHESIS
        "\dFE5B",  # SMALL LEFT CURLY BRACKET
        "\dFE5C",  # SMALL LEFT CURLY BRACKET
        "\dFE5C",  # SMALL RIGHT CURLY BRACKET
        "\dFE5B",  # SMALL RIGHT CURLY BRACKET
        "\dFE5D",  # SMALL LEFT TORTOISE SHELL BRACKET
        "\dFE5E",  # SMALL LEFT TORTOISE SHELL BRACKET
        "\dFE5E",  # SMALL RIGHT TORTOISE SHELL BRACKET
        "\dFE5D",  # SMALL RIGHT TORTOISE SHELL BRACKET
        "\dFF08",  # FULLWIDTH LEFT PARENTHESIS
        "\dFF09",  # FULLWIDTH LEFT PARENTHESIS
        "\dFF09",  # FULLWIDTH RIGHT PARENTHESIS
        "\dFF08",  # FULLWIDTH RIGHT PARENTHESIS
        "\dFF3B",  # FULLWIDTH LEFT SQUARE BRACKET
        "\dFF3D",  # FULLWIDTH LEFT SQUARE BRACKET
        "\dFF3D",  # FULLWIDTH RIGHT SQUARE BRACKET
        "\dFF3B",  # FULLWIDTH RIGHT SQUARE BRACKET
        "\dFF5B",  # FULLWIDTH LEFT CURLY BRACKET
        "\dFF5D",  # FULLWIDTH LEFT CURLY BRACKET
        "\dFF5D",  # FULLWIDTH RIGHT CURLY BRACKET
        "\dFF5B",  # FULLWIDTH RIGHT CURLY BRACKET
        "\dFF5F",  # FULLWIDTH LEFT WHITE PARENTHESIS
        "\dFF60",  # FULLWIDTH LEFT WHITE PARENTHESIS
        "\dFF60",  # FULLWIDTH RIGHT WHITE PARENTHESIS
        "\dFF5F",  # FULLWIDTH RIGHT WHITE PARENTHESIS
        "\dFF62",  # HALFWIDTH LEFT CORNER BRACKET
        "\dFF63",  # HALFWIDTH LEFT CORNER BRACKET
        "\dFF63",  # HALFWIDTH RIGHT CORNER BRACKET
        "\dFF62",  # HALFWIDTH RIGHT CORNER BRACKET
    ]
    test_data.each do |string|
      assert @validator.valid_encoding?(string), "U10_BidiBrackets: #{string}"
      assert string.force_encoding("UTF-8").valid_encoding?, "U10_BidiBrackets: #{string}" if @vercheck
    end
  end

end
