# encoding: utf-8
#
# This file is machine generated.  DO NOT EDIT!
#
if Kernel.respond_to?(:require_relative)
  require_relative("./helper")
else
  $:.unshift(File.dirname(__FILE__))
  require 'helper'
end
#
# == Purpose
#
# Tests for the #{UTF8::Validator} implementation.
#
# Test data pulled and generated from:
#
# https://www.unicode.org/Public/10.0.0/ucd/
#
class TestUnicode10BidiMirroring < Test::Unit::TestCase
  #
  def setup
    @validator = UTF8::Validator.new
    @vercheck = ((RUBY_VERSION =~ /1.9/) or (RUBY_VERSION =~ /2./)) ? true : false
  end

  #
  def teardown
    @validator = nil
  end

  def test_unicode10_BidiMirroring
    test_data = [
      "\d0028",  # LEFT PARENTHESIS
      "\d0029",  # LEFT PARENTHESIS
      "\d0029",  # RIGHT PARENTHESIS
      "\d0028",  # RIGHT PARENTHESIS
      "\d003C",  # LESS-THAN SIGN
      "\d003E",  # LESS-THAN SIGN
      "\d003E",  # GREATER-THAN SIGN
      "\d003C",  # GREATER-THAN SIGN
      "\d005B",  # LEFT SQUARE BRACKET
      "\d005D",  # LEFT SQUARE BRACKET
      "\d005D",  # RIGHT SQUARE BRACKET
      "\d005B",  # RIGHT SQUARE BRACKET
      "\d007B",  # LEFT CURLY BRACKET
      "\d007D",  # LEFT CURLY BRACKET
      "\d007D",  # RIGHT CURLY BRACKET
      "\d007B",  # RIGHT CURLY BRACKET
      "\d00AB",  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
      "\d00BB",  # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
      "\d00BB",  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
      "\d00AB",  # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
      "\d0F3A",  # TIBETAN MARK GUG RTAGS GYON
      "\d0F3B",  # TIBETAN MARK GUG RTAGS GYON
      "\d0F3B",  # TIBETAN MARK GUG RTAGS GYAS
      "\d0F3A",  # TIBETAN MARK GUG RTAGS GYAS
      "\d0F3C",  # TIBETAN MARK ANG KHANG GYON
      "\d0F3D",  # TIBETAN MARK ANG KHANG GYON
      "\d0F3D",  # TIBETAN MARK ANG KHANG GYAS
      "\d0F3C",  # TIBETAN MARK ANG KHANG GYAS
      "\d169B",  # OGHAM FEATHER MARK
      "\d169C",  # OGHAM FEATHER MARK
      "\d169C",  # OGHAM REVERSED FEATHER MARK
      "\d169B",  # OGHAM REVERSED FEATHER MARK
      "\d2039",  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
      "\d203A",  # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
      "\d203A",  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
      "\d2039",  # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
      "\d2045",  # LEFT SQUARE BRACKET WITH QUILL
      "\d2046",  # LEFT SQUARE BRACKET WITH QUILL
      "\d2046",  # RIGHT SQUARE BRACKET WITH QUILL
      "\d2045",  # RIGHT SQUARE BRACKET WITH QUILL
      "\d207D",  # SUPERSCRIPT LEFT PARENTHESIS
      "\d207E",  # SUPERSCRIPT LEFT PARENTHESIS
      "\d207E",  # SUPERSCRIPT RIGHT PARENTHESIS
      "\d207D",  # SUPERSCRIPT RIGHT PARENTHESIS
      "\d208D",  # SUBSCRIPT LEFT PARENTHESIS
      "\d208E",  # SUBSCRIPT LEFT PARENTHESIS
      "\d208E",  # SUBSCRIPT RIGHT PARENTHESIS
      "\d208D",  # SUBSCRIPT RIGHT PARENTHESIS
      "\d2208",  # ELEMENT OF
      "\d220B",  # ELEMENT OF
      "\d2209",  # NOT AN ELEMENT OF
      "\d220C",  # NOT AN ELEMENT OF
      "\d220A",  # SMALL ELEMENT OF
      "\d220D",  # SMALL ELEMENT OF
      "\d220B",  # CONTAINS AS MEMBER
      "\d2208",  # CONTAINS AS MEMBER
      "\d220C",  # DOES NOT CONTAIN AS MEMBER
      "\d2209",  # DOES NOT CONTAIN AS MEMBER
      "\d220D",  # SMALL CONTAINS AS MEMBER
      "\d220A",  # SMALL CONTAINS AS MEMBER
      "\d2215",  # DIVISION SLASH
      "\d29F5",  # DIVISION SLASH
      "\d223C",  # TILDE OPERATOR
      "\d223D",  # TILDE OPERATOR
      "\d223D",  # REVERSED TILDE
      "\d223C",  # REVERSED TILDE
      "\d2243",  # ASYMPTOTICALLY EQUAL TO
      "\d22CD",  # ASYMPTOTICALLY EQUAL TO
      "\d2252",  # APPROXIMATELY EQUAL TO OR THE IMAGE OF
      "\d2253",  # APPROXIMATELY EQUAL TO OR THE IMAGE OF
      "\d2253",  # IMAGE OF OR APPROXIMATELY EQUAL TO
      "\d2252",  # IMAGE OF OR APPROXIMATELY EQUAL TO
      "\d2254",  # COLON EQUALS
      "\d2255",  # COLON EQUALS
      "\d2255",  # EQUALS COLON
      "\d2254",  # EQUALS COLON
      "\d2264",  # LESS-THAN OR EQUAL TO
      "\d2265",  # LESS-THAN OR EQUAL TO
      "\d2265",  # GREATER-THAN OR EQUAL TO
      "\d2264",  # GREATER-THAN OR EQUAL TO
      "\d2266",  # LESS-THAN OVER EQUAL TO
      "\d2267",  # LESS-THAN OVER EQUAL TO
      "\d2267",  # GREATER-THAN OVER EQUAL TO
      "\d2266",  # GREATER-THAN OVER EQUAL TO
      "\d2268",  # [BEST FIT] LESS-THAN BUT NOT EQUAL TO
      "\d2269",  # [BEST FIT] LESS-THAN BUT NOT EQUAL TO
      "\d2269",  # [BEST FIT] GREATER-THAN BUT NOT EQUAL TO
      "\d2268",  # [BEST FIT] GREATER-THAN BUT NOT EQUAL TO
      "\d226A",  # MUCH LESS-THAN
      "\d226B",  # MUCH LESS-THAN
      "\d226B",  # MUCH GREATER-THAN
      "\d226A",  # MUCH GREATER-THAN
      "\d226E",  # [BEST FIT] NOT LESS-THAN
      "\d226F",  # [BEST FIT] NOT LESS-THAN
      "\d226F",  # [BEST FIT] NOT GREATER-THAN
      "\d226E",  # [BEST FIT] NOT GREATER-THAN
      "\d2270",  # [BEST FIT] NEITHER LESS-THAN NOR EQUAL TO
      "\d2271",  # [BEST FIT] NEITHER LESS-THAN NOR EQUAL TO
      "\d2271",  # [BEST FIT] NEITHER GREATER-THAN NOR EQUAL TO
      "\d2270",  # [BEST FIT] NEITHER GREATER-THAN NOR EQUAL TO
      "\d2272",  # [BEST FIT] LESS-THAN OR EQUIVALENT TO
      "\d2273",  # [BEST FIT] LESS-THAN OR EQUIVALENT TO
      "\d2273",  # [BEST FIT] GREATER-THAN OR EQUIVALENT TO
      "\d2272",  # [BEST FIT] GREATER-THAN OR EQUIVALENT TO
      "\d2274",  # [BEST FIT] NEITHER LESS-THAN NOR EQUIVALENT TO
      "\d2275",  # [BEST FIT] NEITHER LESS-THAN NOR EQUIVALENT TO
      "\d2275",  # [BEST FIT] NEITHER GREATER-THAN NOR EQUIVALENT TO
      "\d2274",  # [BEST FIT] NEITHER GREATER-THAN NOR EQUIVALENT TO
      "\d2276",  # LESS-THAN OR GREATER-THAN
      "\d2277",  # LESS-THAN OR GREATER-THAN
      "\d2277",  # GREATER-THAN OR LESS-THAN
      "\d2276",  # GREATER-THAN OR LESS-THAN
      "\d2278",  # [BEST FIT] NEITHER LESS-THAN NOR GREATER-THAN
      "\d2279",  # [BEST FIT] NEITHER LESS-THAN NOR GREATER-THAN
      "\d2279",  # [BEST FIT] NEITHER GREATER-THAN NOR LESS-THAN
      "\d2278",  # [BEST FIT] NEITHER GREATER-THAN NOR LESS-THAN
      "\d227A",  # PRECEDES
      "\d227B",  # PRECEDES
      "\d227B",  # SUCCEEDS
      "\d227A",  # SUCCEEDS
      "\d227C",  # PRECEDES OR EQUAL TO
      "\d227D",  # PRECEDES OR EQUAL TO
      "\d227D",  # SUCCEEDS OR EQUAL TO
      "\d227C",  # SUCCEEDS OR EQUAL TO
      "\d227E",  # [BEST FIT] PRECEDES OR EQUIVALENT TO
      "\d227F",  # [BEST FIT] PRECEDES OR EQUIVALENT TO
      "\d227F",  # [BEST FIT] SUCCEEDS OR EQUIVALENT TO
      "\d227E",  # [BEST FIT] SUCCEEDS OR EQUIVALENT TO
      "\d2280",  # [BEST FIT] DOES NOT PRECEDE
      "\d2281",  # [BEST FIT] DOES NOT PRECEDE
      "\d2281",  # [BEST FIT] DOES NOT SUCCEED
      "\d2280",  # [BEST FIT] DOES NOT SUCCEED
      "\d2282",  # SUBSET OF
      "\d2283",  # SUBSET OF
      "\d2283",  # SUPERSET OF
      "\d2282",  # SUPERSET OF
      "\d2284",  # [BEST FIT] NOT A SUBSET OF
      "\d2285",  # [BEST FIT] NOT A SUBSET OF
      "\d2285",  # [BEST FIT] NOT A SUPERSET OF
      "\d2284",  # [BEST FIT] NOT A SUPERSET OF
      "\d2286",  # SUBSET OF OR EQUAL TO
      "\d2287",  # SUBSET OF OR EQUAL TO
      "\d2287",  # SUPERSET OF OR EQUAL TO
      "\d2286",  # SUPERSET OF OR EQUAL TO
      "\d2288",  # [BEST FIT] NEITHER A SUBSET OF NOR EQUAL TO
      "\d2289",  # [BEST FIT] NEITHER A SUBSET OF NOR EQUAL TO
      "\d2289",  # [BEST FIT] NEITHER A SUPERSET OF NOR EQUAL TO
      "\d2288",  # [BEST FIT] NEITHER A SUPERSET OF NOR EQUAL TO
      "\d228A",  # [BEST FIT] SUBSET OF WITH NOT EQUAL TO
      "\d228B",  # [BEST FIT] SUBSET OF WITH NOT EQUAL TO
      "\d228B",  # [BEST FIT] SUPERSET OF WITH NOT EQUAL TO
      "\d228A",  # [BEST FIT] SUPERSET OF WITH NOT EQUAL TO
      "\d228F",  # SQUARE IMAGE OF
      "\d2290",  # SQUARE IMAGE OF
      "\d2290",  # SQUARE ORIGINAL OF
      "\d228F",  # SQUARE ORIGINAL OF
      "\d2291",  # SQUARE IMAGE OF OR EQUAL TO
      "\d2292",  # SQUARE IMAGE OF OR EQUAL TO
      "\d2292",  # SQUARE ORIGINAL OF OR EQUAL TO
      "\d2291",  # SQUARE ORIGINAL OF OR EQUAL TO
      "\d2298",  # CIRCLED DIVISION SLASH
      "\d29B8",  # CIRCLED DIVISION SLASH
      "\d22A2",  # RIGHT TACK
      "\d22A3",  # RIGHT TACK
      "\d22A3",  # LEFT TACK
      "\d22A2",  # LEFT TACK
      "\d22A6",  # ASSERTION
      "\d2ADE",  # ASSERTION
      "\d22A8",  # TRUE
      "\d2AE4",  # TRUE
      "\d22A9",  # FORCES
      "\d2AE3",  # FORCES
      "\d22AB",  # DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
      "\d2AE5",  # DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE
      "\d22B0",  # PRECEDES UNDER RELATION
      "\d22B1",  # PRECEDES UNDER RELATION
      "\d22B1",  # SUCCEEDS UNDER RELATION
      "\d22B0",  # SUCCEEDS UNDER RELATION
      "\d22B2",  # NORMAL SUBGROUP OF
      "\d22B3",  # NORMAL SUBGROUP OF
      "\d22B3",  # CONTAINS AS NORMAL SUBGROUP
      "\d22B2",  # CONTAINS AS NORMAL SUBGROUP
      "\d22B4",  # NORMAL SUBGROUP OF OR EQUAL TO
      "\d22B5",  # NORMAL SUBGROUP OF OR EQUAL TO
      "\d22B5",  # CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
      "\d22B4",  # CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
      "\d22B6",  # ORIGINAL OF
      "\d22B7",  # ORIGINAL OF
      "\d22B7",  # IMAGE OF
      "\d22B6",  # IMAGE OF
      "\d22C9",  # LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
      "\d22CA",  # LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
      "\d22CA",  # RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
      "\d22C9",  # RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
      "\d22CB",  # LEFT SEMIDIRECT PRODUCT
      "\d22CC",  # LEFT SEMIDIRECT PRODUCT
      "\d22CC",  # RIGHT SEMIDIRECT PRODUCT
      "\d22CB",  # RIGHT SEMIDIRECT PRODUCT
      "\d22CD",  # REVERSED TILDE EQUALS
      "\d2243",  # REVERSED TILDE EQUALS
      "\d22D0",  # DOUBLE SUBSET
      "\d22D1",  # DOUBLE SUBSET
      "\d22D1",  # DOUBLE SUPERSET
      "\d22D0",  # DOUBLE SUPERSET
      "\d22D6",  # LESS-THAN WITH DOT
      "\d22D7",  # LESS-THAN WITH DOT
      "\d22D7",  # GREATER-THAN WITH DOT
      "\d22D6",  # GREATER-THAN WITH DOT
      "\d22D8",  # VERY MUCH LESS-THAN
      "\d22D9",  # VERY MUCH LESS-THAN
      "\d22D9",  # VERY MUCH GREATER-THAN
      "\d22D8",  # VERY MUCH GREATER-THAN
      "\d22DA",  # LESS-THAN EQUAL TO OR GREATER-THAN
      "\d22DB",  # LESS-THAN EQUAL TO OR GREATER-THAN
      "\d22DB",  # GREATER-THAN EQUAL TO OR LESS-THAN
      "\d22DA",  # GREATER-THAN EQUAL TO OR LESS-THAN
      "\d22DC",  # EQUAL TO OR LESS-THAN
      "\d22DD",  # EQUAL TO OR LESS-THAN
      "\d22DD",  # EQUAL TO OR GREATER-THAN
      "\d22DC",  # EQUAL TO OR GREATER-THAN
      "\d22DE",  # EQUAL TO OR PRECEDES
      "\d22DF",  # EQUAL TO OR PRECEDES
      "\d22DF",  # EQUAL TO OR SUCCEEDS
      "\d22DE",  # EQUAL TO OR SUCCEEDS
      "\d22E0",  # [BEST FIT] DOES NOT PRECEDE OR EQUAL
      "\d22E1",  # [BEST FIT] DOES NOT PRECEDE OR EQUAL
      "\d22E1",  # [BEST FIT] DOES NOT SUCCEED OR EQUAL
      "\d22E0",  # [BEST FIT] DOES NOT SUCCEED OR EQUAL
      "\d22E2",  # [BEST FIT] NOT SQUARE IMAGE OF OR EQUAL TO
      "\d22E3",  # [BEST FIT] NOT SQUARE IMAGE OF OR EQUAL TO
      "\d22E3",  # [BEST FIT] NOT SQUARE ORIGINAL OF OR EQUAL TO
      "\d22E2",  # [BEST FIT] NOT SQUARE ORIGINAL OF OR EQUAL TO
      "\d22E4",  # [BEST FIT] SQUARE IMAGE OF OR NOT EQUAL TO
      "\d22E5",  # [BEST FIT] SQUARE IMAGE OF OR NOT EQUAL TO
      "\d22E5",  # [BEST FIT] SQUARE ORIGINAL OF OR NOT EQUAL TO
      "\d22E4",  # [BEST FIT] SQUARE ORIGINAL OF OR NOT EQUAL TO
      "\d22E6",  # [BEST FIT] LESS-THAN BUT NOT EQUIVALENT TO
      "\d22E7",  # [BEST FIT] LESS-THAN BUT NOT EQUIVALENT TO
      "\d22E7",  # [BEST FIT] GREATER-THAN BUT NOT EQUIVALENT TO
      "\d22E6",  # [BEST FIT] GREATER-THAN BUT NOT EQUIVALENT TO
      "\d22E8",  # [BEST FIT] PRECEDES BUT NOT EQUIVALENT TO
      "\d22E9",  # [BEST FIT] PRECEDES BUT NOT EQUIVALENT TO
      "\d22E9",  # [BEST FIT] SUCCEEDS BUT NOT EQUIVALENT TO
      "\d22E8",  # [BEST FIT] SUCCEEDS BUT NOT EQUIVALENT TO
      "\d22EA",  # [BEST FIT] NOT NORMAL SUBGROUP OF
      "\d22EB",  # [BEST FIT] NOT NORMAL SUBGROUP OF
      "\d22EB",  # [BEST FIT] DOES NOT CONTAIN AS NORMAL SUBGROUP
      "\d22EA",  # [BEST FIT] DOES NOT CONTAIN AS NORMAL SUBGROUP
      "\d22EC",  # [BEST FIT] NOT NORMAL SUBGROUP OF OR EQUAL TO
      "\d22ED",  # [BEST FIT] NOT NORMAL SUBGROUP OF OR EQUAL TO
      "\d22ED",  # [BEST FIT] DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
      "\d22EC",  # [BEST FIT] DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
      "\d22F0",  # UP RIGHT DIAGONAL ELLIPSIS
      "\d22F1",  # UP RIGHT DIAGONAL ELLIPSIS
      "\d22F1",  # DOWN RIGHT DIAGONAL ELLIPSIS
      "\d22F0",  # DOWN RIGHT DIAGONAL ELLIPSIS
      "\d22F2",  # ELEMENT OF WITH LONG HORIZONTAL STROKE
      "\d22FA",  # ELEMENT OF WITH LONG HORIZONTAL STROKE
      "\d22F3",  # ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22FB",  # ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22F4",  # SMALL ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22FC",  # SMALL ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22F6",  # ELEMENT OF WITH OVERBAR
      "\d22FD",  # ELEMENT OF WITH OVERBAR
      "\d22F7",  # SMALL ELEMENT OF WITH OVERBAR
      "\d22FE",  # SMALL ELEMENT OF WITH OVERBAR
      "\d22FA",  # CONTAINS WITH LONG HORIZONTAL STROKE
      "\d22F2",  # CONTAINS WITH LONG HORIZONTAL STROKE
      "\d22FB",  # CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22F3",  # CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22FC",  # SMALL CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22F4",  # SMALL CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE
      "\d22FD",  # CONTAINS WITH OVERBAR
      "\d22F6",  # CONTAINS WITH OVERBAR
      "\d22FE",  # SMALL CONTAINS WITH OVERBAR
      "\d22F7",  # SMALL CONTAINS WITH OVERBAR
      "\d2308",  # LEFT CEILING
      "\d2309",  # LEFT CEILING
      "\d2309",  # RIGHT CEILING
      "\d2308",  # RIGHT CEILING
      "\d230A",  # LEFT FLOOR
      "\d230B",  # LEFT FLOOR
      "\d230B",  # RIGHT FLOOR
      "\d230A",  # RIGHT FLOOR
      "\d2329",  # LEFT-POINTING ANGLE BRACKET
      "\d232A",  # LEFT-POINTING ANGLE BRACKET
      "\d232A",  # RIGHT-POINTING ANGLE BRACKET
      "\d2329",  # RIGHT-POINTING ANGLE BRACKET
      "\d2768",  # MEDIUM LEFT PARENTHESIS ORNAMENT
      "\d2769",  # MEDIUM LEFT PARENTHESIS ORNAMENT
      "\d2769",  # MEDIUM RIGHT PARENTHESIS ORNAMENT
      "\d2768",  # MEDIUM RIGHT PARENTHESIS ORNAMENT
      "\d276A",  # MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
      "\d276B",  # MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
      "\d276B",  # MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
      "\d276A",  # MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
      "\d276C",  # MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
      "\d276D",  # MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
      "\d276D",  # MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
      "\d276C",  # MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
      "\d276E",  # HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
      "\d276F",  # HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
      "\d276F",  # HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
      "\d276E",  # HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
      "\d2770",  # HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
      "\d2771",  # HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
      "\d2771",  # HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
      "\d2770",  # HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
      "\d2772",  # LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT
      "\d2773",  # LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT
      "\d2773",  # LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
      "\d2772",  # LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
      "\d2774",  # MEDIUM LEFT CURLY BRACKET ORNAMENT
      "\d2775",  # MEDIUM LEFT CURLY BRACKET ORNAMENT
      "\d2775",  # MEDIUM RIGHT CURLY BRACKET ORNAMENT
      "\d2774",  # MEDIUM RIGHT CURLY BRACKET ORNAMENT
      "\d27C3",  # OPEN SUBSET
      "\d27C4",  # OPEN SUBSET
      "\d27C4",  # OPEN SUPERSET
      "\d27C3",  # OPEN SUPERSET
      "\d27C5",  # LEFT S-SHAPED BAG DELIMITER
      "\d27C6",  # LEFT S-SHAPED BAG DELIMITER
      "\d27C6",  # RIGHT S-SHAPED BAG DELIMITER
      "\d27C5",  # RIGHT S-SHAPED BAG DELIMITER
      "\d27C8",  # REVERSE SOLIDUS PRECEDING SUBSET
      "\d27C9",  # REVERSE SOLIDUS PRECEDING SUBSET
      "\d27C9",  # SUPERSET PRECEDING SOLIDUS
      "\d27C8",  # SUPERSET PRECEDING SOLIDUS
      "\d27CB",  # MATHEMATICAL RISING DIAGONAL
      "\d27CD",  # MATHEMATICAL RISING DIAGONAL
      "\d27CD",  # MATHEMATICAL FALLING DIAGONAL
      "\d27CB",  # MATHEMATICAL FALLING DIAGONAL
      "\d27D5",  # LEFT OUTER JOIN
      "\d27D6",  # LEFT OUTER JOIN
      "\d27D6",  # RIGHT OUTER JOIN
      "\d27D5",  # RIGHT OUTER JOIN
      "\d27DD",  # LONG RIGHT TACK
      "\d27DE",  # LONG RIGHT TACK
      "\d27DE",  # LONG LEFT TACK
      "\d27DD",  # LONG LEFT TACK
      "\d27E2",  # WHITE CONCAVE-SIDED DIAMOND WITH LEFTWARDS TICK
      "\d27E3",  # WHITE CONCAVE-SIDED DIAMOND WITH LEFTWARDS TICK
      "\d27E3",  # WHITE CONCAVE-SIDED DIAMOND WITH RIGHTWARDS TICK
      "\d27E2",  # WHITE CONCAVE-SIDED DIAMOND WITH RIGHTWARDS TICK
      "\d27E4",  # WHITE SQUARE WITH LEFTWARDS TICK
      "\d27E5",  # WHITE SQUARE WITH LEFTWARDS TICK
      "\d27E5",  # WHITE SQUARE WITH RIGHTWARDS TICK
      "\d27E4",  # WHITE SQUARE WITH RIGHTWARDS TICK
      "\d27E6",  # MATHEMATICAL LEFT WHITE SQUARE BRACKET
      "\d27E7",  # MATHEMATICAL LEFT WHITE SQUARE BRACKET
      "\d27E7",  # MATHEMATICAL RIGHT WHITE SQUARE BRACKET
      "\d27E6",  # MATHEMATICAL RIGHT WHITE SQUARE BRACKET
      "\d27E8",  # MATHEMATICAL LEFT ANGLE BRACKET
      "\d27E9",  # MATHEMATICAL LEFT ANGLE BRACKET
      "\d27E9",  # MATHEMATICAL RIGHT ANGLE BRACKET
      "\d27E8",  # MATHEMATICAL RIGHT ANGLE BRACKET
      "\d27EA",  # MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
      "\d27EB",  # MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
      "\d27EB",  # MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
      "\d27EA",  # MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
      "\d27EC",  # MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
      "\d27ED",  # MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
      "\d27ED",  # MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
      "\d27EC",  # MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
      "\d27EE",  # MATHEMATICAL LEFT FLATTENED PARENTHESIS
      "\d27EF",  # MATHEMATICAL LEFT FLATTENED PARENTHESIS
      "\d27EF",  # MATHEMATICAL RIGHT FLATTENED PARENTHESIS
      "\d27EE",  # MATHEMATICAL RIGHT FLATTENED PARENTHESIS
      "\d2983",  # LEFT WHITE CURLY BRACKET
      "\d2984",  # LEFT WHITE CURLY BRACKET
      "\d2984",  # RIGHT WHITE CURLY BRACKET
      "\d2983",  # RIGHT WHITE CURLY BRACKET
      "\d2985",  # LEFT WHITE PARENTHESIS
      "\d2986",  # LEFT WHITE PARENTHESIS
      "\d2986",  # RIGHT WHITE PARENTHESIS
      "\d2985",  # RIGHT WHITE PARENTHESIS
      "\d2987",  # Z NOTATION LEFT IMAGE BRACKET
      "\d2988",  # Z NOTATION LEFT IMAGE BRACKET
      "\d2988",  # Z NOTATION RIGHT IMAGE BRACKET
      "\d2987",  # Z NOTATION RIGHT IMAGE BRACKET
      "\d2989",  # Z NOTATION LEFT BINDING BRACKET
      "\d298A",  # Z NOTATION LEFT BINDING BRACKET
      "\d298A",  # Z NOTATION RIGHT BINDING BRACKET
      "\d2989",  # Z NOTATION RIGHT BINDING BRACKET
      "\d298B",  # LEFT SQUARE BRACKET WITH UNDERBAR
      "\d298C",  # LEFT SQUARE BRACKET WITH UNDERBAR
      "\d298C",  # RIGHT SQUARE BRACKET WITH UNDERBAR
      "\d298B",  # RIGHT SQUARE BRACKET WITH UNDERBAR
      "\d298D",  # LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
      "\d2990",  # LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
      "\d298E",  # RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
      "\d298F",  # RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
      "\d298F",  # LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
      "\d298E",  # LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
      "\d2990",  # RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
      "\d298D",  # RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
      "\d2991",  # LEFT ANGLE BRACKET WITH DOT
      "\d2992",  # LEFT ANGLE BRACKET WITH DOT
      "\d2992",  # RIGHT ANGLE BRACKET WITH DOT
      "\d2991",  # RIGHT ANGLE BRACKET WITH DOT
      "\d2993",  # LEFT ARC LESS-THAN BRACKET
      "\d2994",  # LEFT ARC LESS-THAN BRACKET
      "\d2994",  # RIGHT ARC GREATER-THAN BRACKET
      "\d2993",  # RIGHT ARC GREATER-THAN BRACKET
      "\d2995",  # DOUBLE LEFT ARC GREATER-THAN BRACKET
      "\d2996",  # DOUBLE LEFT ARC GREATER-THAN BRACKET
      "\d2996",  # DOUBLE RIGHT ARC LESS-THAN BRACKET
      "\d2995",  # DOUBLE RIGHT ARC LESS-THAN BRACKET
      "\d2997",  # LEFT BLACK TORTOISE SHELL BRACKET
      "\d2998",  # LEFT BLACK TORTOISE SHELL BRACKET
      "\d2998",  # RIGHT BLACK TORTOISE SHELL BRACKET
      "\d2997",  # RIGHT BLACK TORTOISE SHELL BRACKET
      "\d29B8",  # CIRCLED REVERSE SOLIDUS
      "\d2298",  # CIRCLED REVERSE SOLIDUS
      "\d29C0",  # CIRCLED LESS-THAN
      "\d29C1",  # CIRCLED LESS-THAN
      "\d29C1",  # CIRCLED GREATER-THAN
      "\d29C0",  # CIRCLED GREATER-THAN
      "\d29C4",  # SQUARED RISING DIAGONAL SLASH
      "\d29C5",  # SQUARED RISING DIAGONAL SLASH
      "\d29C5",  # SQUARED FALLING DIAGONAL SLASH
      "\d29C4",  # SQUARED FALLING DIAGONAL SLASH
      "\d29CF",  # LEFT TRIANGLE BESIDE VERTICAL BAR
      "\d29D0",  # LEFT TRIANGLE BESIDE VERTICAL BAR
      "\d29D0",  # VERTICAL BAR BESIDE RIGHT TRIANGLE
      "\d29CF",  # VERTICAL BAR BESIDE RIGHT TRIANGLE
      "\d29D1",  # BOWTIE WITH LEFT HALF BLACK
      "\d29D2",  # BOWTIE WITH LEFT HALF BLACK
      "\d29D2",  # BOWTIE WITH RIGHT HALF BLACK
      "\d29D1",  # BOWTIE WITH RIGHT HALF BLACK
      "\d29D4",  # TIMES WITH LEFT HALF BLACK
      "\d29D5",  # TIMES WITH LEFT HALF BLACK
      "\d29D5",  # TIMES WITH RIGHT HALF BLACK
      "\d29D4",  # TIMES WITH RIGHT HALF BLACK
      "\d29D8",  # LEFT WIGGLY FENCE
      "\d29D9",  # LEFT WIGGLY FENCE
      "\d29D9",  # RIGHT WIGGLY FENCE
      "\d29D8",  # RIGHT WIGGLY FENCE
      "\d29DA",  # LEFT DOUBLE WIGGLY FENCE
      "\d29DB",  # LEFT DOUBLE WIGGLY FENCE
      "\d29DB",  # RIGHT DOUBLE WIGGLY FENCE
      "\d29DA",  # RIGHT DOUBLE WIGGLY FENCE
      "\d29F5",  # REVERSE SOLIDUS OPERATOR
      "\d2215",  # REVERSE SOLIDUS OPERATOR
      "\d29F8",  # BIG SOLIDUS
      "\d29F9",  # BIG SOLIDUS
      "\d29F9",  # BIG REVERSE SOLIDUS
      "\d29F8",  # BIG REVERSE SOLIDUS
      "\d29FC",  # LEFT-POINTING CURVED ANGLE BRACKET
      "\d29FD",  # LEFT-POINTING CURVED ANGLE BRACKET
      "\d29FD",  # RIGHT-POINTING CURVED ANGLE BRACKET
      "\d29FC",  # RIGHT-POINTING CURVED ANGLE BRACKET
      "\d2A2B",  # MINUS SIGN WITH FALLING DOTS
      "\d2A2C",  # MINUS SIGN WITH FALLING DOTS
      "\d2A2C",  # MINUS SIGN WITH RISING DOTS
      "\d2A2B",  # MINUS SIGN WITH RISING DOTS
      "\d2A2D",  # PLUS SIGN IN LEFT HALF CIRCLE
      "\d2A2E",  # PLUS SIGN IN LEFT HALF CIRCLE
      "\d2A2E",  # PLUS SIGN IN RIGHT HALF CIRCLE
      "\d2A2D",  # PLUS SIGN IN RIGHT HALF CIRCLE
      "\d2A34",  # MULTIPLICATION SIGN IN LEFT HALF CIRCLE
      "\d2A35",  # MULTIPLICATION SIGN IN LEFT HALF CIRCLE
      "\d2A35",  # MULTIPLICATION SIGN IN RIGHT HALF CIRCLE
      "\d2A34",  # MULTIPLICATION SIGN IN RIGHT HALF CIRCLE
      "\d2A3C",  # INTERIOR PRODUCT
      "\d2A3D",  # INTERIOR PRODUCT
      "\d2A3D",  # RIGHTHAND INTERIOR PRODUCT
      "\d2A3C",  # RIGHTHAND INTERIOR PRODUCT
      "\d2A64",  # Z NOTATION DOMAIN ANTIRESTRICTION
      "\d2A65",  # Z NOTATION DOMAIN ANTIRESTRICTION
      "\d2A65",  # Z NOTATION RANGE ANTIRESTRICTION
      "\d2A64",  # Z NOTATION RANGE ANTIRESTRICTION
      "\d2A79",  # LESS-THAN WITH CIRCLE INSIDE
      "\d2A7A",  # LESS-THAN WITH CIRCLE INSIDE
      "\d2A7A",  # GREATER-THAN WITH CIRCLE INSIDE
      "\d2A79",  # GREATER-THAN WITH CIRCLE INSIDE
      "\d2A7D",  # LESS-THAN OR SLANTED EQUAL TO
      "\d2A7E",  # LESS-THAN OR SLANTED EQUAL TO
      "\d2A7E",  # GREATER-THAN OR SLANTED EQUAL TO
      "\d2A7D",  # GREATER-THAN OR SLANTED EQUAL TO
      "\d2A7F",  # LESS-THAN OR SLANTED EQUAL TO WITH DOT INSIDE
      "\d2A80",  # LESS-THAN OR SLANTED EQUAL TO WITH DOT INSIDE
      "\d2A80",  # GREATER-THAN OR SLANTED EQUAL TO WITH DOT INSIDE
      "\d2A7F",  # GREATER-THAN OR SLANTED EQUAL TO WITH DOT INSIDE
      "\d2A81",  # LESS-THAN OR SLANTED EQUAL TO WITH DOT ABOVE
      "\d2A82",  # LESS-THAN OR SLANTED EQUAL TO WITH DOT ABOVE
      "\d2A82",  # GREATER-THAN OR SLANTED EQUAL TO WITH DOT ABOVE
      "\d2A81",  # GREATER-THAN OR SLANTED EQUAL TO WITH DOT ABOVE
      "\d2A83",  # LESS-THAN OR SLANTED EQUAL TO WITH DOT ABOVE RIGHT
      "\d2A84",  # LESS-THAN OR SLANTED EQUAL TO WITH DOT ABOVE RIGHT
      "\d2A84",  # GREATER-THAN OR SLANTED EQUAL TO WITH DOT ABOVE LEFT
      "\d2A83",  # GREATER-THAN OR SLANTED EQUAL TO WITH DOT ABOVE LEFT
      "\d2A8B",  # LESS-THAN ABOVE DOUBLE-LINE EQUAL ABOVE GREATER-THAN
      "\d2A8C",  # LESS-THAN ABOVE DOUBLE-LINE EQUAL ABOVE GREATER-THAN
      "\d2A8C",  # GREATER-THAN ABOVE DOUBLE-LINE EQUAL ABOVE LESS-THAN
      "\d2A8B",  # GREATER-THAN ABOVE DOUBLE-LINE EQUAL ABOVE LESS-THAN
      "\d2A91",  # LESS-THAN ABOVE GREATER-THAN ABOVE DOUBLE-LINE EQUAL
      "\d2A92",  # LESS-THAN ABOVE GREATER-THAN ABOVE DOUBLE-LINE EQUAL
      "\d2A92",  # GREATER-THAN ABOVE LESS-THAN ABOVE DOUBLE-LINE EQUAL
      "\d2A91",  # GREATER-THAN ABOVE LESS-THAN ABOVE DOUBLE-LINE EQUAL
      "\d2A93",  # LESS-THAN ABOVE SLANTED EQUAL ABOVE GREATER-THAN ABOVE SLANTED EQUAL
      "\d2A94",  # LESS-THAN ABOVE SLANTED EQUAL ABOVE GREATER-THAN ABOVE SLANTED EQUAL
      "\d2A94",  # GREATER-THAN ABOVE SLANTED EQUAL ABOVE LESS-THAN ABOVE SLANTED EQUAL
      "\d2A93",  # GREATER-THAN ABOVE SLANTED EQUAL ABOVE LESS-THAN ABOVE SLANTED EQUAL
      "\d2A95",  # SLANTED EQUAL TO OR LESS-THAN
      "\d2A96",  # SLANTED EQUAL TO OR LESS-THAN
      "\d2A96",  # SLANTED EQUAL TO OR GREATER-THAN
      "\d2A95",  # SLANTED EQUAL TO OR GREATER-THAN
      "\d2A97",  # SLANTED EQUAL TO OR LESS-THAN WITH DOT INSIDE
      "\d2A98",  # SLANTED EQUAL TO OR LESS-THAN WITH DOT INSIDE
      "\d2A98",  # SLANTED EQUAL TO OR GREATER-THAN WITH DOT INSIDE
      "\d2A97",  # SLANTED EQUAL TO OR GREATER-THAN WITH DOT INSIDE
      "\d2A99",  # DOUBLE-LINE EQUAL TO OR LESS-THAN
      "\d2A9A",  # DOUBLE-LINE EQUAL TO OR LESS-THAN
      "\d2A9A",  # DOUBLE-LINE EQUAL TO OR GREATER-THAN
      "\d2A99",  # DOUBLE-LINE EQUAL TO OR GREATER-THAN
      "\d2A9B",  # DOUBLE-LINE SLANTED EQUAL TO OR LESS-THAN
      "\d2A9C",  # DOUBLE-LINE SLANTED EQUAL TO OR LESS-THAN
      "\d2A9C",  # DOUBLE-LINE SLANTED EQUAL TO OR GREATER-THAN
      "\d2A9B",  # DOUBLE-LINE SLANTED EQUAL TO OR GREATER-THAN
      "\d2AA1",  # DOUBLE NESTED LESS-THAN
      "\d2AA2",  # DOUBLE NESTED LESS-THAN
      "\d2AA2",  # DOUBLE NESTED GREATER-THAN
      "\d2AA1",  # DOUBLE NESTED GREATER-THAN
      "\d2AA6",  # LESS-THAN CLOSED BY CURVE
      "\d2AA7",  # LESS-THAN CLOSED BY CURVE
      "\d2AA7",  # GREATER-THAN CLOSED BY CURVE
      "\d2AA6",  # GREATER-THAN CLOSED BY CURVE
      "\d2AA8",  # LESS-THAN CLOSED BY CURVE ABOVE SLANTED EQUAL
      "\d2AA9",  # LESS-THAN CLOSED BY CURVE ABOVE SLANTED EQUAL
      "\d2AA9",  # GREATER-THAN CLOSED BY CURVE ABOVE SLANTED EQUAL
      "\d2AA8",  # GREATER-THAN CLOSED BY CURVE ABOVE SLANTED EQUAL
      "\d2AAA",  # SMALLER THAN
      "\d2AAB",  # SMALLER THAN
      "\d2AAB",  # LARGER THAN
      "\d2AAA",  # LARGER THAN
      "\d2AAC",  # SMALLER THAN OR EQUAL TO
      "\d2AAD",  # SMALLER THAN OR EQUAL TO
      "\d2AAD",  # LARGER THAN OR EQUAL TO
      "\d2AAC",  # LARGER THAN OR EQUAL TO
      "\d2AAF",  # PRECEDES ABOVE SINGLE-LINE EQUALS SIGN
      "\d2AB0",  # PRECEDES ABOVE SINGLE-LINE EQUALS SIGN
      "\d2AB0",  # SUCCEEDS ABOVE SINGLE-LINE EQUALS SIGN
      "\d2AAF",  # SUCCEEDS ABOVE SINGLE-LINE EQUALS SIGN
      "\d2AB3",  # PRECEDES ABOVE EQUALS SIGN
      "\d2AB4",  # PRECEDES ABOVE EQUALS SIGN
      "\d2AB4",  # SUCCEEDS ABOVE EQUALS SIGN
      "\d2AB3",  # SUCCEEDS ABOVE EQUALS SIGN
      "\d2ABB",  # DOUBLE PRECEDES
      "\d2ABC",  # DOUBLE PRECEDES
      "\d2ABC",  # DOUBLE SUCCEEDS
      "\d2ABB",  # DOUBLE SUCCEEDS
      "\d2ABD",  # SUBSET WITH DOT
      "\d2ABE",  # SUBSET WITH DOT
      "\d2ABE",  # SUPERSET WITH DOT
      "\d2ABD",  # SUPERSET WITH DOT
      "\d2ABF",  # SUBSET WITH PLUS SIGN BELOW
      "\d2AC0",  # SUBSET WITH PLUS SIGN BELOW
      "\d2AC0",  # SUPERSET WITH PLUS SIGN BELOW
      "\d2ABF",  # SUPERSET WITH PLUS SIGN BELOW
      "\d2AC1",  # SUBSET WITH MULTIPLICATION SIGN BELOW
      "\d2AC2",  # SUBSET WITH MULTIPLICATION SIGN BELOW
      "\d2AC2",  # SUPERSET WITH MULTIPLICATION SIGN BELOW
      "\d2AC1",  # SUPERSET WITH MULTIPLICATION SIGN BELOW
      "\d2AC3",  # SUBSET OF OR EQUAL TO WITH DOT ABOVE
      "\d2AC4",  # SUBSET OF OR EQUAL TO WITH DOT ABOVE
      "\d2AC4",  # SUPERSET OF OR EQUAL TO WITH DOT ABOVE
      "\d2AC3",  # SUPERSET OF OR EQUAL TO WITH DOT ABOVE
      "\d2AC5",  # SUBSET OF ABOVE EQUALS SIGN
      "\d2AC6",  # SUBSET OF ABOVE EQUALS SIGN
      "\d2AC6",  # SUPERSET OF ABOVE EQUALS SIGN
      "\d2AC5",  # SUPERSET OF ABOVE EQUALS SIGN
      "\d2ACD",  # SQUARE LEFT OPEN BOX OPERATOR
      "\d2ACE",  # SQUARE LEFT OPEN BOX OPERATOR
      "\d2ACE",  # SQUARE RIGHT OPEN BOX OPERATOR
      "\d2ACD",  # SQUARE RIGHT OPEN BOX OPERATOR
      "\d2ACF",  # CLOSED SUBSET
      "\d2AD0",  # CLOSED SUBSET
      "\d2AD0",  # CLOSED SUPERSET
      "\d2ACF",  # CLOSED SUPERSET
      "\d2AD1",  # CLOSED SUBSET OR EQUAL TO
      "\d2AD2",  # CLOSED SUBSET OR EQUAL TO
      "\d2AD2",  # CLOSED SUPERSET OR EQUAL TO
      "\d2AD1",  # CLOSED SUPERSET OR EQUAL TO
      "\d2AD3",  # SUBSET ABOVE SUPERSET
      "\d2AD4",  # SUBSET ABOVE SUPERSET
      "\d2AD4",  # SUPERSET ABOVE SUBSET
      "\d2AD3",  # SUPERSET ABOVE SUBSET
      "\d2AD5",  # SUBSET ABOVE SUBSET
      "\d2AD6",  # SUBSET ABOVE SUBSET
      "\d2AD6",  # SUPERSET ABOVE SUPERSET
      "\d2AD5",  # SUPERSET ABOVE SUPERSET
      "\d2ADE",  # SHORT LEFT TACK
      "\d22A6",  # SHORT LEFT TACK
      "\d2AE3",  # DOUBLE VERTICAL BAR LEFT TURNSTILE
      "\d22A9",  # DOUBLE VERTICAL BAR LEFT TURNSTILE
      "\d2AE4",  # VERTICAL BAR DOUBLE LEFT TURNSTILE
      "\d22A8",  # VERTICAL BAR DOUBLE LEFT TURNSTILE
      "\d2AE5",  # DOUBLE VERTICAL BAR DOUBLE LEFT TURNSTILE
      "\d22AB",  # DOUBLE VERTICAL BAR DOUBLE LEFT TURNSTILE
      "\d2AEC",  # DOUBLE STROKE NOT SIGN
      "\d2AED",  # DOUBLE STROKE NOT SIGN
      "\d2AED",  # REVERSED DOUBLE STROKE NOT SIGN
      "\d2AEC",  # REVERSED DOUBLE STROKE NOT SIGN
      "\d2AF7",  # TRIPLE NESTED LESS-THAN
      "\d2AF8",  # TRIPLE NESTED LESS-THAN
      "\d2AF8",  # TRIPLE NESTED GREATER-THAN
      "\d2AF7",  # TRIPLE NESTED GREATER-THAN
      "\d2AF9",  # DOUBLE-LINE SLANTED LESS-THAN OR EQUAL TO
      "\d2AFA",  # DOUBLE-LINE SLANTED LESS-THAN OR EQUAL TO
      "\d2AFA",  # DOUBLE-LINE SLANTED GREATER-THAN OR EQUAL TO
      "\d2AF9",  # DOUBLE-LINE SLANTED GREATER-THAN OR EQUAL TO
      "\d2E02",  # LEFT SUBSTITUTION BRACKET
      "\d2E03",  # LEFT SUBSTITUTION BRACKET
      "\d2E03",  # RIGHT SUBSTITUTION BRACKET
      "\d2E02",  # RIGHT SUBSTITUTION BRACKET
      "\d2E04",  # LEFT DOTTED SUBSTITUTION BRACKET
      "\d2E05",  # LEFT DOTTED SUBSTITUTION BRACKET
      "\d2E05",  # RIGHT DOTTED SUBSTITUTION BRACKET
      "\d2E04",  # RIGHT DOTTED SUBSTITUTION BRACKET
      "\d2E09",  # LEFT TRANSPOSITION BRACKET
      "\d2E0A",  # LEFT TRANSPOSITION BRACKET
      "\d2E0A",  # RIGHT TRANSPOSITION BRACKET
      "\d2E09",  # RIGHT TRANSPOSITION BRACKET
      "\d2E0C",  # LEFT RAISED OMISSION BRACKET
      "\d2E0D",  # LEFT RAISED OMISSION BRACKET
      "\d2E0D",  # RIGHT RAISED OMISSION BRACKET
      "\d2E0C",  # RIGHT RAISED OMISSION BRACKET
      "\d2E1C",  # LEFT LOW PARAPHRASE BRACKET
      "\d2E1D",  # LEFT LOW PARAPHRASE BRACKET
      "\d2E1D",  # RIGHT LOW PARAPHRASE BRACKET
      "\d2E1C",  # RIGHT LOW PARAPHRASE BRACKET
      "\d2E20",  # LEFT VERTICAL BAR WITH QUILL
      "\d2E21",  # LEFT VERTICAL BAR WITH QUILL
      "\d2E21",  # RIGHT VERTICAL BAR WITH QUILL
      "\d2E20",  # RIGHT VERTICAL BAR WITH QUILL
      "\d2E22",  # TOP LEFT HALF BRACKET
      "\d2E23",  # TOP LEFT HALF BRACKET
      "\d2E23",  # TOP RIGHT HALF BRACKET
      "\d2E22",  # TOP RIGHT HALF BRACKET
      "\d2E24",  # BOTTOM LEFT HALF BRACKET
      "\d2E25",  # BOTTOM LEFT HALF BRACKET
      "\d2E25",  # BOTTOM RIGHT HALF BRACKET
      "\d2E24",  # BOTTOM RIGHT HALF BRACKET
      "\d2E26",  # LEFT SIDEWAYS U BRACKET
      "\d2E27",  # LEFT SIDEWAYS U BRACKET
      "\d2E27",  # RIGHT SIDEWAYS U BRACKET
      "\d2E26",  # RIGHT SIDEWAYS U BRACKET
      "\d2E28",  # LEFT DOUBLE PARENTHESIS
      "\d2E29",  # LEFT DOUBLE PARENTHESIS
      "\d2E29",  # RIGHT DOUBLE PARENTHESIS
      "\d2E28",  # RIGHT DOUBLE PARENTHESIS
      "\d3008",  # LEFT ANGLE BRACKET
      "\d3009",  # LEFT ANGLE BRACKET
      "\d3009",  # RIGHT ANGLE BRACKET
      "\d3008",  # RIGHT ANGLE BRACKET
      "\d300A",  # LEFT DOUBLE ANGLE BRACKET
      "\d300B",  # LEFT DOUBLE ANGLE BRACKET
      "\d300B",  # RIGHT DOUBLE ANGLE BRACKET
      "\d300A",  # RIGHT DOUBLE ANGLE BRACKET
      "\d300C",  # [BEST FIT] LEFT CORNER BRACKET
      "\d300D",  # [BEST FIT] LEFT CORNER BRACKET
      "\d300D",  # [BEST FIT] RIGHT CORNER BRACKET
      "\d300C",  # [BEST FIT] RIGHT CORNER BRACKET
      "\d300E",  # [BEST FIT] LEFT WHITE CORNER BRACKET
      "\d300F",  # [BEST FIT] LEFT WHITE CORNER BRACKET
      "\d300F",  # [BEST FIT] RIGHT WHITE CORNER BRACKET
      "\d300E",  # [BEST FIT] RIGHT WHITE CORNER BRACKET
      "\d3010",  # LEFT BLACK LENTICULAR BRACKET
      "\d3011",  # LEFT BLACK LENTICULAR BRACKET
      "\d3011",  # RIGHT BLACK LENTICULAR BRACKET
      "\d3010",  # RIGHT BLACK LENTICULAR BRACKET
      "\d3014",  # LEFT TORTOISE SHELL BRACKET
      "\d3015",  # LEFT TORTOISE SHELL BRACKET
      "\d3015",  # RIGHT TORTOISE SHELL BRACKET
      "\d3014",  # RIGHT TORTOISE SHELL BRACKET
      "\d3016",  # LEFT WHITE LENTICULAR BRACKET
      "\d3017",  # LEFT WHITE LENTICULAR BRACKET
      "\d3017",  # RIGHT WHITE LENTICULAR BRACKET
      "\d3016",  # RIGHT WHITE LENTICULAR BRACKET
      "\d3018",  # LEFT WHITE TORTOISE SHELL BRACKET
      "\d3019",  # LEFT WHITE TORTOISE SHELL BRACKET
      "\d3019",  # RIGHT WHITE TORTOISE SHELL BRACKET
      "\d3018",  # RIGHT WHITE TORTOISE SHELL BRACKET
      "\d301A",  # LEFT WHITE SQUARE BRACKET
      "\d301B",  # LEFT WHITE SQUARE BRACKET
      "\d301B",  # RIGHT WHITE SQUARE BRACKET
      "\d301A",  # RIGHT WHITE SQUARE BRACKET
      "\dFE59",  # SMALL LEFT PARENTHESIS
      "\dFE5A",  # SMALL LEFT PARENTHESIS
      "\dFE5A",  # SMALL RIGHT PARENTHESIS
      "\dFE59",  # SMALL RIGHT PARENTHESIS
      "\dFE5B",  # SMALL LEFT CURLY BRACKET
      "\dFE5C",  # SMALL LEFT CURLY BRACKET
      "\dFE5C",  # SMALL RIGHT CURLY BRACKET
      "\dFE5B",  # SMALL RIGHT CURLY BRACKET
      "\dFE5D",  # SMALL LEFT TORTOISE SHELL BRACKET
      "\dFE5E",  # SMALL LEFT TORTOISE SHELL BRACKET
      "\dFE5E",  # SMALL RIGHT TORTOISE SHELL BRACKET
      "\dFE5D",  # SMALL RIGHT TORTOISE SHELL BRACKET
      "\dFE64",  # SMALL LESS-THAN SIGN
      "\dFE65",  # SMALL LESS-THAN SIGN
      "\dFE65",  # SMALL GREATER-THAN SIGN
      "\dFE64",  # SMALL GREATER-THAN SIGN
      "\dFF08",  # FULLWIDTH LEFT PARENTHESIS
      "\dFF09",  # FULLWIDTH LEFT PARENTHESIS
      "\dFF09",  # FULLWIDTH RIGHT PARENTHESIS
      "\dFF08",  # FULLWIDTH RIGHT PARENTHESIS
      "\dFF1C",  # FULLWIDTH LESS-THAN SIGN
      "\dFF1E",  # FULLWIDTH LESS-THAN SIGN
      "\dFF1E",  # FULLWIDTH GREATER-THAN SIGN
      "\dFF1C",  # FULLWIDTH GREATER-THAN SIGN
      "\dFF3B",  # FULLWIDTH LEFT SQUARE BRACKET
      "\dFF3D",  # FULLWIDTH LEFT SQUARE BRACKET
      "\dFF3D",  # FULLWIDTH RIGHT SQUARE BRACKET
      "\dFF3B",  # FULLWIDTH RIGHT SQUARE BRACKET
      "\dFF5B",  # FULLWIDTH LEFT CURLY BRACKET
      "\dFF5D",  # FULLWIDTH LEFT CURLY BRACKET
      "\dFF5D",  # FULLWIDTH RIGHT CURLY BRACKET
      "\dFF5B",  # FULLWIDTH RIGHT CURLY BRACKET
      "\dFF5F",  # FULLWIDTH LEFT WHITE PARENTHESIS
      "\dFF60",  # FULLWIDTH LEFT WHITE PARENTHESIS
      "\dFF60",  # FULLWIDTH RIGHT WHITE PARENTHESIS
      "\dFF5F",  # FULLWIDTH RIGHT WHITE PARENTHESIS
      "\dFF62",  # [BEST FIT] HALFWIDTH LEFT CORNER BRACKET
      "\dFF63",  # [BEST FIT] HALFWIDTH LEFT CORNER BRACKET
      "\dFF63",  # [BEST FIT] HALFWIDTH RIGHT CORNER BRACKET
      "\dFF62",  # [BEST FIT] HALFWIDTH RIGHT CORNER BRACKET
    ]
    test_data.each do |string|
      assert @validator.valid_encoding?(string), "U10_BidiMirroring: #{string}"
      assert string.force_encoding("UTF-8").valid_encoding?, "U10_BidiMirroring: #{string}" if @vercheck
    end
  end

end
