# encoding: utf-8
#
# This file is machine generated.  DO NOT EDIT!
#
if Kernel.respond_to?(:require_relative)
  require_relative("./helper")
else
  $:.unshift(File.dirname(__FILE__))
  require 'helper'
end
#
# == Purpose
#
# Tests for the #{UTF8::Validator} implementation.
#
# Test data pulled and generated from:
#
# https://www.unicode.org/Public/10.0.0/ucd/
#
class TestUnicode10NamedSequences < Test::Unit::TestCase
  #
  def setup
    @validator = UTF8::Validator.new
    @vercheck = ((RUBY_VERSION =~ /1.9/) or (RUBY_VERSION =~ /2./)) ? true : false
  end

  #
  def teardown
    @validator = nil
  end

  def test_unicode10_NamedSequences
    test_data = [
      "\d0023",  # KEYCAP NUMBER SIGN
      "\dFE0F",  # KEYCAP NUMBER SIGN
      "\d20E3",  # KEYCAP NUMBER SIGN
      "\d002A",  # KEYCAP ASTERISK
      "\dFE0F",  # KEYCAP ASTERISK
      "\d20E3",  # KEYCAP ASTERISK
      "\d0030",  # KEYCAP DIGIT ZERO
      "\dFE0F",  # KEYCAP DIGIT ZERO
      "\d20E3",  # KEYCAP DIGIT ZERO
      "\d0031",  # KEYCAP DIGIT ONE
      "\dFE0F",  # KEYCAP DIGIT ONE
      "\d20E3",  # KEYCAP DIGIT ONE
      "\d0032",  # KEYCAP DIGIT TWO
      "\dFE0F",  # KEYCAP DIGIT TWO
      "\d20E3",  # KEYCAP DIGIT TWO
      "\d0033",  # KEYCAP DIGIT THREE
      "\dFE0F",  # KEYCAP DIGIT THREE
      "\d20E3",  # KEYCAP DIGIT THREE
      "\d0034",  # KEYCAP DIGIT FOUR
      "\dFE0F",  # KEYCAP DIGIT FOUR
      "\d20E3",  # KEYCAP DIGIT FOUR
      "\d0035",  # KEYCAP DIGIT FIVE
      "\dFE0F",  # KEYCAP DIGIT FIVE
      "\d20E3",  # KEYCAP DIGIT FIVE
      "\d0036",  # KEYCAP DIGIT SIX
      "\dFE0F",  # KEYCAP DIGIT SIX
      "\d20E3",  # KEYCAP DIGIT SIX
      "\d0037",  # KEYCAP DIGIT SEVEN
      "\dFE0F",  # KEYCAP DIGIT SEVEN
      "\d20E3",  # KEYCAP DIGIT SEVEN
      "\d0038",  # KEYCAP DIGIT EIGHT
      "\dFE0F",  # KEYCAP DIGIT EIGHT
      "\d20E3",  # KEYCAP DIGIT EIGHT
      "\d0039",  # KEYCAP DIGIT NINE
      "\dFE0F",  # KEYCAP DIGIT NINE
      "\d20E3",  # KEYCAP DIGIT NINE
      "\d0100",  # LATIN CAPITAL LETTER A WITH MACRON AND GRAVE
      "\d0300",  # LATIN CAPITAL LETTER A WITH MACRON AND GRAVE
      "\d0101",  # LATIN SMALL LETTER A WITH MACRON AND GRAVE
      "\d0300",  # LATIN SMALL LETTER A WITH MACRON AND GRAVE
      "\d0045",  # LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW
      "\d0329",  # LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW
      "\d0065",  # LATIN SMALL LETTER E WITH VERTICAL LINE BELOW
      "\d0329",  # LATIN SMALL LETTER E WITH VERTICAL LINE BELOW
      "\d00C8",  # LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW AND GRAVE
      "\d0329",  # LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW AND GRAVE
      "\d00E8",  # LATIN SMALL LETTER E WITH VERTICAL LINE BELOW AND GRAVE
      "\d0329",  # LATIN SMALL LETTER E WITH VERTICAL LINE BELOW AND GRAVE
      "\d00C9",  # LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW AND ACUTE
      "\d0329",  # LATIN CAPITAL LETTER E WITH VERTICAL LINE BELOW AND ACUTE
      "\d00E9",  # LATIN SMALL LETTER E WITH VERTICAL LINE BELOW AND ACUTE
      "\d0329",  # LATIN SMALL LETTER E WITH VERTICAL LINE BELOW AND ACUTE
      "\d00CA",  # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND MACRON
      "\d0304",  # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND MACRON
      "\d00EA",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND MACRON
      "\d0304",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND MACRON
      "\d00CA",  # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND CARON
      "\d030C",  # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND CARON
      "\d00EA",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND CARON
      "\d030C",  # LATIN SMALL LETTER E WITH CIRCUMFLEX AND CARON
      "\d012A",  # LATIN CAPITAL LETTER I WITH MACRON AND GRAVE
      "\d0300",  # LATIN CAPITAL LETTER I WITH MACRON AND GRAVE
      "\d012B",  # LATIN SMALL LETTER I WITH MACRON AND GRAVE
      "\d0300",  # LATIN SMALL LETTER I WITH MACRON AND GRAVE
      "\d0069",  # LATIN SMALL LETTER I WITH DOT ABOVE AND ACUTE
      "\d0307",  # LATIN SMALL LETTER I WITH DOT ABOVE AND ACUTE
      "\d0301",  # LATIN SMALL LETTER I WITH DOT ABOVE AND ACUTE
      "\d006E",  # LATIN SMALL LETTER NG WITH TILDE ABOVE
      "\d0360",  # LATIN SMALL LETTER NG WITH TILDE ABOVE
      "\d0067",  # LATIN SMALL LETTER NG WITH TILDE ABOVE
      "\d004F",  # LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW
      "\d0329",  # LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW
      "\d006F",  # LATIN SMALL LETTER O WITH VERTICAL LINE BELOW
      "\d0329",  # LATIN SMALL LETTER O WITH VERTICAL LINE BELOW
      "\d00D2",  # LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW AND GRAVE
      "\d0329",  # LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW AND GRAVE
      "\d00F2",  # LATIN SMALL LETTER O WITH VERTICAL LINE BELOW AND GRAVE
      "\d0329",  # LATIN SMALL LETTER O WITH VERTICAL LINE BELOW AND GRAVE
      "\d00D3",  # LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW AND ACUTE
      "\d0329",  # LATIN CAPITAL LETTER O WITH VERTICAL LINE BELOW AND ACUTE
      "\d00F3",  # LATIN SMALL LETTER O WITH VERTICAL LINE BELOW AND ACUTE
      "\d0329",  # LATIN SMALL LETTER O WITH VERTICAL LINE BELOW AND ACUTE
      "\d0053",  # LATIN CAPITAL LETTER S WITH VERTICAL LINE BELOW
      "\d0329",  # LATIN CAPITAL LETTER S WITH VERTICAL LINE BELOW
      "\d0073",  # LATIN SMALL LETTER S WITH VERTICAL LINE BELOW
      "\d0329",  # LATIN SMALL LETTER S WITH VERTICAL LINE BELOW
      "\d016A",  # LATIN CAPITAL LETTER U WITH MACRON AND GRAVE
      "\d0300",  # LATIN CAPITAL LETTER U WITH MACRON AND GRAVE
      "\d016B",  # LATIN SMALL LETTER U WITH MACRON AND GRAVE
      "\d0300",  # LATIN SMALL LETTER U WITH MACRON AND GRAVE
      "\d0104",  # LATIN CAPITAL LETTER A WITH OGONEK AND ACUTE
      "\d0301",  # LATIN CAPITAL LETTER A WITH OGONEK AND ACUTE
      "\d0105",  # LATIN SMALL LETTER A WITH OGONEK AND ACUTE
      "\d0301",  # LATIN SMALL LETTER A WITH OGONEK AND ACUTE
      "\d0104",  # LATIN CAPITAL LETTER A WITH OGONEK AND TILDE
      "\d0303",  # LATIN CAPITAL LETTER A WITH OGONEK AND TILDE
      "\d0105",  # LATIN SMALL LETTER A WITH OGONEK AND TILDE
      "\d0303",  # LATIN SMALL LETTER A WITH OGONEK AND TILDE
      "\d0118",  # LATIN CAPITAL LETTER E WITH OGONEK AND ACUTE
      "\d0301",  # LATIN CAPITAL LETTER E WITH OGONEK AND ACUTE
      "\d0119",  # LATIN SMALL LETTER E WITH OGONEK AND ACUTE
      "\d0301",  # LATIN SMALL LETTER E WITH OGONEK AND ACUTE
      "\d0118",  # LATIN CAPITAL LETTER E WITH OGONEK AND TILDE
      "\d0303",  # LATIN CAPITAL LETTER E WITH OGONEK AND TILDE
      "\d0119",  # LATIN SMALL LETTER E WITH OGONEK AND TILDE
      "\d0303",  # LATIN SMALL LETTER E WITH OGONEK AND TILDE
      "\d0116",  # LATIN CAPITAL LETTER E WITH DOT ABOVE AND ACUTE
      "\d0301",  # LATIN CAPITAL LETTER E WITH DOT ABOVE AND ACUTE
      "\d0117",  # LATIN SMALL LETTER E WITH DOT ABOVE AND ACUTE
      "\d0301",  # LATIN SMALL LETTER E WITH DOT ABOVE AND ACUTE
      "\d0116",  # LATIN CAPITAL LETTER E WITH DOT ABOVE AND TILDE
      "\d0303",  # LATIN CAPITAL LETTER E WITH DOT ABOVE AND TILDE
      "\d0117",  # LATIN SMALL LETTER E WITH DOT ABOVE AND TILDE
      "\d0303",  # LATIN SMALL LETTER E WITH DOT ABOVE AND TILDE
      "\d0069",  # LATIN SMALL LETTER I WITH DOT ABOVE AND GRAVE
      "\d0307",  # LATIN SMALL LETTER I WITH DOT ABOVE AND GRAVE
      "\d0300",  # LATIN SMALL LETTER I WITH DOT ABOVE AND GRAVE
      "\d0069",  # LATIN SMALL LETTER I WITH DOT ABOVE AND TILDE
      "\d0307",  # LATIN SMALL LETTER I WITH DOT ABOVE AND TILDE
      "\d0303",  # LATIN SMALL LETTER I WITH DOT ABOVE AND TILDE
      "\d012E",  # LATIN CAPITAL LETTER I WITH OGONEK AND ACUTE
      "\d0301",  # LATIN CAPITAL LETTER I WITH OGONEK AND ACUTE
      "\d012F",  # LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND ACUTE
      "\d0307",  # LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND ACUTE
      "\d0301",  # LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND ACUTE
      "\d012E",  # LATIN CAPITAL LETTER I WITH OGONEK AND TILDE
      "\d0303",  # LATIN CAPITAL LETTER I WITH OGONEK AND TILDE
      "\d012F",  # LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND TILDE
      "\d0307",  # LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND TILDE
      "\d0303",  # LATIN SMALL LETTER I WITH OGONEK AND DOT ABOVE AND TILDE
      "\d004A",  # LATIN CAPITAL LETTER J WITH TILDE
      "\d0303",  # LATIN CAPITAL LETTER J WITH TILDE
      "\d006A",  # LATIN SMALL LETTER J WITH DOT ABOVE AND TILDE
      "\d0307",  # LATIN SMALL LETTER J WITH DOT ABOVE AND TILDE
      "\d0303",  # LATIN SMALL LETTER J WITH DOT ABOVE AND TILDE
      "\d004C",  # LATIN CAPITAL LETTER L WITH TILDE
      "\d0303",  # LATIN CAPITAL LETTER L WITH TILDE
      "\d006C",  # LATIN SMALL LETTER L WITH TILDE
      "\d0303",  # LATIN SMALL LETTER L WITH TILDE
      "\d004D",  # LATIN CAPITAL LETTER M WITH TILDE
      "\d0303",  # LATIN CAPITAL LETTER M WITH TILDE
      "\d006D",  # LATIN SMALL LETTER M WITH TILDE
      "\d0303",  # LATIN SMALL LETTER M WITH TILDE
      "\d0052",  # LATIN CAPITAL LETTER R WITH TILDE
      "\d0303",  # LATIN CAPITAL LETTER R WITH TILDE
      "\d0072",  # LATIN SMALL LETTER R WITH TILDE
      "\d0303",  # LATIN SMALL LETTER R WITH TILDE
      "\d0172",  # LATIN CAPITAL LETTER U WITH OGONEK AND ACUTE
      "\d0301",  # LATIN CAPITAL LETTER U WITH OGONEK AND ACUTE
      "\d0173",  # LATIN SMALL LETTER U WITH OGONEK AND ACUTE
      "\d0301",  # LATIN SMALL LETTER U WITH OGONEK AND ACUTE
      "\d0172",  # LATIN CAPITAL LETTER U WITH OGONEK AND TILDE
      "\d0303",  # LATIN CAPITAL LETTER U WITH OGONEK AND TILDE
      "\d0173",  # LATIN SMALL LETTER U WITH OGONEK AND TILDE
      "\d0303",  # LATIN SMALL LETTER U WITH OGONEK AND TILDE
      "\d016A",  # LATIN CAPITAL LETTER U WITH MACRON AND ACUTE
      "\d0301",  # LATIN CAPITAL LETTER U WITH MACRON AND ACUTE
      "\d016B",  # LATIN SMALL LETTER U WITH MACRON AND ACUTE
      "\d0301",  # LATIN SMALL LETTER U WITH MACRON AND ACUTE
      "\d016A",  # LATIN CAPITAL LETTER U WITH MACRON AND TILDE
      "\d0303",  # LATIN CAPITAL LETTER U WITH MACRON AND TILDE
      "\d016B",  # LATIN SMALL LETTER U WITH MACRON AND TILDE
      "\d0303",  # LATIN SMALL LETTER U WITH MACRON AND TILDE
      "\d00E6",  # LATIN SMALL LETTER AE WITH GRAVE
      "\d0300",  # LATIN SMALL LETTER AE WITH GRAVE
      "\d0254",  # LATIN SMALL LETTER OPEN O WITH GRAVE
      "\d0300",  # LATIN SMALL LETTER OPEN O WITH GRAVE
      "\d0254",  # LATIN SMALL LETTER OPEN O WITH ACUTE
      "\d0301",  # LATIN SMALL LETTER OPEN O WITH ACUTE
      "\d028C",  # LATIN SMALL LETTER TURNED V WITH GRAVE
      "\d0300",  # LATIN SMALL LETTER TURNED V WITH GRAVE
      "\d028C",  # LATIN SMALL LETTER TURNED V WITH ACUTE
      "\d0301",  # LATIN SMALL LETTER TURNED V WITH ACUTE
      "\d0259",  # LATIN SMALL LETTER SCHWA WITH GRAVE
      "\d0300",  # LATIN SMALL LETTER SCHWA WITH GRAVE
      "\d0259",  # LATIN SMALL LETTER SCHWA WITH ACUTE
      "\d0301",  # LATIN SMALL LETTER SCHWA WITH ACUTE
      "\d025A",  # LATIN SMALL LETTER HOOKED SCHWA WITH GRAVE
      "\d0300",  # LATIN SMALL LETTER HOOKED SCHWA WITH GRAVE
      "\d025A",  # LATIN SMALL LETTER HOOKED SCHWA WITH ACUTE
      "\d0301",  # LATIN SMALL LETTER HOOKED SCHWA WITH ACUTE
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH ALEF
      "\d0627",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH ALEF
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH WAW
      "\d0648",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH WAW
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA
      "\d0649",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH OE
      "\d06C6",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH OE
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH U
      "\d06C7",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH U
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH YU
      "\d06C8",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH YU
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH E
      "\d06D0",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH E
      "\d0626",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH AE
      "\d06D5",  # ARABIC SEQUENCE YEH WITH HAMZA ABOVE WITH AE
      "\d0646",  # ARABIC SEQUENCE NOON WITH KEHEH
      "\d06A9",  # ARABIC SEQUENCE NOON WITH KEHEH
      "\d0995",  # BENGALI LETTER KHINYA
      "\d09CD",  # BENGALI LETTER KHINYA
      "\d09B7",  # BENGALI LETTER KHINYA
      "\d0B95",  # TAMIL CONSONANT K
      "\d0BCD",  # TAMIL CONSONANT K
      "\d0B99",  # TAMIL CONSONANT NG
      "\d0BCD",  # TAMIL CONSONANT NG
      "\d0B9A",  # TAMIL CONSONANT C
      "\d0BCD",  # TAMIL CONSONANT C
      "\d0B9E",  # TAMIL CONSONANT NY
      "\d0BCD",  # TAMIL CONSONANT NY
      "\d0B9F",  # TAMIL CONSONANT TT
      "\d0BCD",  # TAMIL CONSONANT TT
      "\d0BA3",  # TAMIL CONSONANT NN
      "\d0BCD",  # TAMIL CONSONANT NN
      "\d0BA4",  # TAMIL CONSONANT T
      "\d0BCD",  # TAMIL CONSONANT T
      "\d0BA8",  # TAMIL CONSONANT N
      "\d0BCD",  # TAMIL CONSONANT N
      "\d0BAA",  # TAMIL CONSONANT P
      "\d0BCD",  # TAMIL CONSONANT P
      "\d0BAE",  # TAMIL CONSONANT M
      "\d0BCD",  # TAMIL CONSONANT M
      "\d0BAF",  # TAMIL CONSONANT Y
      "\d0BCD",  # TAMIL CONSONANT Y
      "\d0BB0",  # TAMIL CONSONANT R
      "\d0BCD",  # TAMIL CONSONANT R
      "\d0BB2",  # TAMIL CONSONANT L
      "\d0BCD",  # TAMIL CONSONANT L
      "\d0BB5",  # TAMIL CONSONANT V
      "\d0BCD",  # TAMIL CONSONANT V
      "\d0BB4",  # TAMIL CONSONANT LLL
      "\d0BCD",  # TAMIL CONSONANT LLL
      "\d0BB3",  # TAMIL CONSONANT LL
      "\d0BCD",  # TAMIL CONSONANT LL
      "\d0BB1",  # TAMIL CONSONANT RR
      "\d0BCD",  # TAMIL CONSONANT RR
      "\d0BA9",  # TAMIL CONSONANT NNN
      "\d0BCD",  # TAMIL CONSONANT NNN
      "\d0B9C",  # TAMIL CONSONANT J
      "\d0BCD",  # TAMIL CONSONANT J
      "\d0BB6",  # TAMIL CONSONANT SH
      "\d0BCD",  # TAMIL CONSONANT SH
      "\d0BB7",  # TAMIL CONSONANT SS
      "\d0BCD",  # TAMIL CONSONANT SS
      "\d0BB8",  # TAMIL CONSONANT S
      "\d0BCD",  # TAMIL CONSONANT S
      "\d0BB9",  # TAMIL CONSONANT H
      "\d0BCD",  # TAMIL CONSONANT H
      "\d0B95",  # TAMIL CONSONANT KSS
      "\d0BCD",  # TAMIL CONSONANT KSS
      "\d0BB7",  # TAMIL CONSONANT KSS
      "\d0BCD",  # TAMIL CONSONANT KSS
      "\d0B95",  # TAMIL SYLLABLE KAA
      "\d0BBE",  # TAMIL SYLLABLE KAA
      "\d0B95",  # TAMIL SYLLABLE KI
      "\d0BBF",  # TAMIL SYLLABLE KI
      "\d0B95",  # TAMIL SYLLABLE KII
      "\d0BC0",  # TAMIL SYLLABLE KII
      "\d0B95",  # TAMIL SYLLABLE KU
      "\d0BC1",  # TAMIL SYLLABLE KU
      "\d0B95",  # TAMIL SYLLABLE KUU
      "\d0BC2",  # TAMIL SYLLABLE KUU
      "\d0B95",  # TAMIL SYLLABLE KE
      "\d0BC6",  # TAMIL SYLLABLE KE
      "\d0B95",  # TAMIL SYLLABLE KEE
      "\d0BC7",  # TAMIL SYLLABLE KEE
      "\d0B95",  # TAMIL SYLLABLE KAI
      "\d0BC8",  # TAMIL SYLLABLE KAI
      "\d0B95",  # TAMIL SYLLABLE KO
      "\d0BCA",  # TAMIL SYLLABLE KO
      "\d0B95",  # TAMIL SYLLABLE KOO
      "\d0BCB",  # TAMIL SYLLABLE KOO
      "\d0B95",  # TAMIL SYLLABLE KAU
      "\d0BCC",  # TAMIL SYLLABLE KAU
      "\d0B99",  # TAMIL SYLLABLE NGAA
      "\d0BBE",  # TAMIL SYLLABLE NGAA
      "\d0B99",  # TAMIL SYLLABLE NGI
      "\d0BBF",  # TAMIL SYLLABLE NGI
      "\d0B99",  # TAMIL SYLLABLE NGII
      "\d0BC0",  # TAMIL SYLLABLE NGII
      "\d0B99",  # TAMIL SYLLABLE NGU
      "\d0BC1",  # TAMIL SYLLABLE NGU
      "\d0B99",  # TAMIL SYLLABLE NGUU
      "\d0BC2",  # TAMIL SYLLABLE NGUU
      "\d0B99",  # TAMIL SYLLABLE NGE
      "\d0BC6",  # TAMIL SYLLABLE NGE
      "\d0B99",  # TAMIL SYLLABLE NGEE
      "\d0BC7",  # TAMIL SYLLABLE NGEE
      "\d0B99",  # TAMIL SYLLABLE NGAI
      "\d0BC8",  # TAMIL SYLLABLE NGAI
      "\d0B99",  # TAMIL SYLLABLE NGO
      "\d0BCA",  # TAMIL SYLLABLE NGO
      "\d0B99",  # TAMIL SYLLABLE NGOO
      "\d0BCB",  # TAMIL SYLLABLE NGOO
      "\d0B99",  # TAMIL SYLLABLE NGAU
      "\d0BCC",  # TAMIL SYLLABLE NGAU
      "\d0B9A",  # TAMIL SYLLABLE CAA
      "\d0BBE",  # TAMIL SYLLABLE CAA
      "\d0B9A",  # TAMIL SYLLABLE CI
      "\d0BBF",  # TAMIL SYLLABLE CI
      "\d0B9A",  # TAMIL SYLLABLE CII
      "\d0BC0",  # TAMIL SYLLABLE CII
      "\d0B9A",  # TAMIL SYLLABLE CU
      "\d0BC1",  # TAMIL SYLLABLE CU
      "\d0B9A",  # TAMIL SYLLABLE CUU
      "\d0BC2",  # TAMIL SYLLABLE CUU
      "\d0B9A",  # TAMIL SYLLABLE CE
      "\d0BC6",  # TAMIL SYLLABLE CE
      "\d0B9A",  # TAMIL SYLLABLE CEE
      "\d0BC7",  # TAMIL SYLLABLE CEE
      "\d0B9A",  # TAMIL SYLLABLE CAI
      "\d0BC8",  # TAMIL SYLLABLE CAI
      "\d0B9A",  # TAMIL SYLLABLE CO
      "\d0BCA",  # TAMIL SYLLABLE CO
      "\d0B9A",  # TAMIL SYLLABLE COO
      "\d0BCB",  # TAMIL SYLLABLE COO
      "\d0B9A",  # TAMIL SYLLABLE CAU
      "\d0BCC",  # TAMIL SYLLABLE CAU
      "\d0B9E",  # TAMIL SYLLABLE NYAA
      "\d0BBE",  # TAMIL SYLLABLE NYAA
      "\d0B9E",  # TAMIL SYLLABLE NYI
      "\d0BBF",  # TAMIL SYLLABLE NYI
      "\d0B9E",  # TAMIL SYLLABLE NYII
      "\d0BC0",  # TAMIL SYLLABLE NYII
      "\d0B9E",  # TAMIL SYLLABLE NYU
      "\d0BC1",  # TAMIL SYLLABLE NYU
      "\d0B9E",  # TAMIL SYLLABLE NYUU
      "\d0BC2",  # TAMIL SYLLABLE NYUU
      "\d0B9E",  # TAMIL SYLLABLE NYE
      "\d0BC6",  # TAMIL SYLLABLE NYE
      "\d0B9E",  # TAMIL SYLLABLE NYEE
      "\d0BC7",  # TAMIL SYLLABLE NYEE
      "\d0B9E",  # TAMIL SYLLABLE NYAI
      "\d0BC8",  # TAMIL SYLLABLE NYAI
      "\d0B9E",  # TAMIL SYLLABLE NYO
      "\d0BCA",  # TAMIL SYLLABLE NYO
      "\d0B9E",  # TAMIL SYLLABLE NYOO
      "\d0BCB",  # TAMIL SYLLABLE NYOO
      "\d0B9E",  # TAMIL SYLLABLE NYAU
      "\d0BCC",  # TAMIL SYLLABLE NYAU
      "\d0B9F",  # TAMIL SYLLABLE TTAA
      "\d0BBE",  # TAMIL SYLLABLE TTAA
      "\d0B9F",  # TAMIL SYLLABLE TTI
      "\d0BBF",  # TAMIL SYLLABLE TTI
      "\d0B9F",  # TAMIL SYLLABLE TTII
      "\d0BC0",  # TAMIL SYLLABLE TTII
      "\d0B9F",  # TAMIL SYLLABLE TTU
      "\d0BC1",  # TAMIL SYLLABLE TTU
      "\d0B9F",  # TAMIL SYLLABLE TTUU
      "\d0BC2",  # TAMIL SYLLABLE TTUU
      "\d0B9F",  # TAMIL SYLLABLE TTE
      "\d0BC6",  # TAMIL SYLLABLE TTE
      "\d0B9F",  # TAMIL SYLLABLE TTEE
      "\d0BC7",  # TAMIL SYLLABLE TTEE
      "\d0B9F",  # TAMIL SYLLABLE TTAI
      "\d0BC8",  # TAMIL SYLLABLE TTAI
      "\d0B9F",  # TAMIL SYLLABLE TTO
      "\d0BCA",  # TAMIL SYLLABLE TTO
      "\d0B9F",  # TAMIL SYLLABLE TTOO
      "\d0BCB",  # TAMIL SYLLABLE TTOO
      "\d0B9F",  # TAMIL SYLLABLE TTAU
      "\d0BCC",  # TAMIL SYLLABLE TTAU
      "\d0BA3",  # TAMIL SYLLABLE NNAA
      "\d0BBE",  # TAMIL SYLLABLE NNAA
      "\d0BA3",  # TAMIL SYLLABLE NNI
      "\d0BBF",  # TAMIL SYLLABLE NNI
      "\d0BA3",  # TAMIL SYLLABLE NNII
      "\d0BC0",  # TAMIL SYLLABLE NNII
      "\d0BA3",  # TAMIL SYLLABLE NNU
      "\d0BC1",  # TAMIL SYLLABLE NNU
      "\d0BA3",  # TAMIL SYLLABLE NNUU
      "\d0BC2",  # TAMIL SYLLABLE NNUU
      "\d0BA3",  # TAMIL SYLLABLE NNE
      "\d0BC6",  # TAMIL SYLLABLE NNE
      "\d0BA3",  # TAMIL SYLLABLE NNEE
      "\d0BC7",  # TAMIL SYLLABLE NNEE
      "\d0BA3",  # TAMIL SYLLABLE NNAI
      "\d0BC8",  # TAMIL SYLLABLE NNAI
      "\d0BA3",  # TAMIL SYLLABLE NNO
      "\d0BCA",  # TAMIL SYLLABLE NNO
      "\d0BA3",  # TAMIL SYLLABLE NNOO
      "\d0BCB",  # TAMIL SYLLABLE NNOO
      "\d0BA3",  # TAMIL SYLLABLE NNAU
      "\d0BCC",  # TAMIL SYLLABLE NNAU
      "\d0BA4",  # TAMIL SYLLABLE TAA
      "\d0BBE",  # TAMIL SYLLABLE TAA
      "\d0BA4",  # TAMIL SYLLABLE TI
      "\d0BBF",  # TAMIL SYLLABLE TI
      "\d0BA4",  # TAMIL SYLLABLE TII
      "\d0BC0",  # TAMIL SYLLABLE TII
      "\d0BA4",  # TAMIL SYLLABLE TU
      "\d0BC1",  # TAMIL SYLLABLE TU
      "\d0BA4",  # TAMIL SYLLABLE TUU
      "\d0BC2",  # TAMIL SYLLABLE TUU
      "\d0BA4",  # TAMIL SYLLABLE TE
      "\d0BC6",  # TAMIL SYLLABLE TE
      "\d0BA4",  # TAMIL SYLLABLE TEE
      "\d0BC7",  # TAMIL SYLLABLE TEE
      "\d0BA4",  # TAMIL SYLLABLE TAI
      "\d0BC8",  # TAMIL SYLLABLE TAI
      "\d0BA4",  # TAMIL SYLLABLE TO
      "\d0BCA",  # TAMIL SYLLABLE TO
      "\d0BA4",  # TAMIL SYLLABLE TOO
      "\d0BCB",  # TAMIL SYLLABLE TOO
      "\d0BA4",  # TAMIL SYLLABLE TAU
      "\d0BCC",  # TAMIL SYLLABLE TAU
      "\d0BA8",  # TAMIL SYLLABLE NAA
      "\d0BBE",  # TAMIL SYLLABLE NAA
      "\d0BA8",  # TAMIL SYLLABLE NI
      "\d0BBF",  # TAMIL SYLLABLE NI
      "\d0BA8",  # TAMIL SYLLABLE NII
      "\d0BC0",  # TAMIL SYLLABLE NII
      "\d0BA8",  # TAMIL SYLLABLE NU
      "\d0BC1",  # TAMIL SYLLABLE NU
      "\d0BA8",  # TAMIL SYLLABLE NUU
      "\d0BC2",  # TAMIL SYLLABLE NUU
      "\d0BA8",  # TAMIL SYLLABLE NE
      "\d0BC6",  # TAMIL SYLLABLE NE
      "\d0BA8",  # TAMIL SYLLABLE NEE
      "\d0BC7",  # TAMIL SYLLABLE NEE
      "\d0BA8",  # TAMIL SYLLABLE NAI
      "\d0BC8",  # TAMIL SYLLABLE NAI
      "\d0BA8",  # TAMIL SYLLABLE NO
      "\d0BCA",  # TAMIL SYLLABLE NO
      "\d0BA8",  # TAMIL SYLLABLE NOO
      "\d0BCB",  # TAMIL SYLLABLE NOO
      "\d0BA8",  # TAMIL SYLLABLE NAU
      "\d0BCC",  # TAMIL SYLLABLE NAU
      "\d0BAA",  # TAMIL SYLLABLE PAA
      "\d0BBE",  # TAMIL SYLLABLE PAA
      "\d0BAA",  # TAMIL SYLLABLE PI
      "\d0BBF",  # TAMIL SYLLABLE PI
      "\d0BAA",  # TAMIL SYLLABLE PII
      "\d0BC0",  # TAMIL SYLLABLE PII
      "\d0BAA",  # TAMIL SYLLABLE PU
      "\d0BC1",  # TAMIL SYLLABLE PU
      "\d0BAA",  # TAMIL SYLLABLE PUU
      "\d0BC2",  # TAMIL SYLLABLE PUU
      "\d0BAA",  # TAMIL SYLLABLE PE
      "\d0BC6",  # TAMIL SYLLABLE PE
      "\d0BAA",  # TAMIL SYLLABLE PEE
      "\d0BC7",  # TAMIL SYLLABLE PEE
      "\d0BAA",  # TAMIL SYLLABLE PAI
      "\d0BC8",  # TAMIL SYLLABLE PAI
      "\d0BAA",  # TAMIL SYLLABLE PO
      "\d0BCA",  # TAMIL SYLLABLE PO
      "\d0BAA",  # TAMIL SYLLABLE POO
      "\d0BCB",  # TAMIL SYLLABLE POO
      "\d0BAA",  # TAMIL SYLLABLE PAU
      "\d0BCC",  # TAMIL SYLLABLE PAU
      "\d0BAE",  # TAMIL SYLLABLE MAA
      "\d0BBE",  # TAMIL SYLLABLE MAA
      "\d0BAE",  # TAMIL SYLLABLE MI
      "\d0BBF",  # TAMIL SYLLABLE MI
      "\d0BAE",  # TAMIL SYLLABLE MII
      "\d0BC0",  # TAMIL SYLLABLE MII
      "\d0BAE",  # TAMIL SYLLABLE MU
      "\d0BC1",  # TAMIL SYLLABLE MU
      "\d0BAE",  # TAMIL SYLLABLE MUU
      "\d0BC2",  # TAMIL SYLLABLE MUU
      "\d0BAE",  # TAMIL SYLLABLE ME
      "\d0BC6",  # TAMIL SYLLABLE ME
      "\d0BAE",  # TAMIL SYLLABLE MEE
      "\d0BC7",  # TAMIL SYLLABLE MEE
      "\d0BAE",  # TAMIL SYLLABLE MAI
      "\d0BC8",  # TAMIL SYLLABLE MAI
      "\d0BAE",  # TAMIL SYLLABLE MO
      "\d0BCA",  # TAMIL SYLLABLE MO
      "\d0BAE",  # TAMIL SYLLABLE MOO
      "\d0BCB",  # TAMIL SYLLABLE MOO
      "\d0BAE",  # TAMIL SYLLABLE MAU
      "\d0BCC",  # TAMIL SYLLABLE MAU
      "\d0BAF",  # TAMIL SYLLABLE YAA
      "\d0BBE",  # TAMIL SYLLABLE YAA
      "\d0BAF",  # TAMIL SYLLABLE YI
      "\d0BBF",  # TAMIL SYLLABLE YI
      "\d0BAF",  # TAMIL SYLLABLE YII
      "\d0BC0",  # TAMIL SYLLABLE YII
      "\d0BAF",  # TAMIL SYLLABLE YU
      "\d0BC1",  # TAMIL SYLLABLE YU
      "\d0BAF",  # TAMIL SYLLABLE YUU
      "\d0BC2",  # TAMIL SYLLABLE YUU
      "\d0BAF",  # TAMIL SYLLABLE YE
      "\d0BC6",  # TAMIL SYLLABLE YE
      "\d0BAF",  # TAMIL SYLLABLE YEE
      "\d0BC7",  # TAMIL SYLLABLE YEE
      "\d0BAF",  # TAMIL SYLLABLE YAI
      "\d0BC8",  # TAMIL SYLLABLE YAI
      "\d0BAF",  # TAMIL SYLLABLE YO
      "\d0BCA",  # TAMIL SYLLABLE YO
      "\d0BAF",  # TAMIL SYLLABLE YOO
      "\d0BCB",  # TAMIL SYLLABLE YOO
      "\d0BAF",  # TAMIL SYLLABLE YAU
      "\d0BCC",  # TAMIL SYLLABLE YAU
      "\d0BB0",  # TAMIL SYLLABLE RAA
      "\d0BBE",  # TAMIL SYLLABLE RAA
      "\d0BB0",  # TAMIL SYLLABLE RI
      "\d0BBF",  # TAMIL SYLLABLE RI
      "\d0BB0",  # TAMIL SYLLABLE RII
      "\d0BC0",  # TAMIL SYLLABLE RII
      "\d0BB0",  # TAMIL SYLLABLE RU
      "\d0BC1",  # TAMIL SYLLABLE RU
      "\d0BB0",  # TAMIL SYLLABLE RUU
      "\d0BC2",  # TAMIL SYLLABLE RUU
      "\d0BB0",  # TAMIL SYLLABLE RE
      "\d0BC6",  # TAMIL SYLLABLE RE
      "\d0BB0",  # TAMIL SYLLABLE REE
      "\d0BC7",  # TAMIL SYLLABLE REE
      "\d0BB0",  # TAMIL SYLLABLE RAI
      "\d0BC8",  # TAMIL SYLLABLE RAI
      "\d0BB0",  # TAMIL SYLLABLE RO
      "\d0BCA",  # TAMIL SYLLABLE RO
      "\d0BB0",  # TAMIL SYLLABLE ROO
      "\d0BCB",  # TAMIL SYLLABLE ROO
      "\d0BB0",  # TAMIL SYLLABLE RAU
      "\d0BCC",  # TAMIL SYLLABLE RAU
      "\d0BB2",  # TAMIL SYLLABLE LAA
      "\d0BBE",  # TAMIL SYLLABLE LAA
      "\d0BB2",  # TAMIL SYLLABLE LI
      "\d0BBF",  # TAMIL SYLLABLE LI
      "\d0BB2",  # TAMIL SYLLABLE LII
      "\d0BC0",  # TAMIL SYLLABLE LII
      "\d0BB2",  # TAMIL SYLLABLE LU
      "\d0BC1",  # TAMIL SYLLABLE LU
      "\d0BB2",  # TAMIL SYLLABLE LUU
      "\d0BC2",  # TAMIL SYLLABLE LUU
      "\d0BB2",  # TAMIL SYLLABLE LE
      "\d0BC6",  # TAMIL SYLLABLE LE
      "\d0BB2",  # TAMIL SYLLABLE LEE
      "\d0BC7",  # TAMIL SYLLABLE LEE
      "\d0BB2",  # TAMIL SYLLABLE LAI
      "\d0BC8",  # TAMIL SYLLABLE LAI
      "\d0BB2",  # TAMIL SYLLABLE LO
      "\d0BCA",  # TAMIL SYLLABLE LO
      "\d0BB2",  # TAMIL SYLLABLE LOO
      "\d0BCB",  # TAMIL SYLLABLE LOO
      "\d0BB2",  # TAMIL SYLLABLE LAU
      "\d0BCC",  # TAMIL SYLLABLE LAU
      "\d0BB5",  # TAMIL SYLLABLE VAA
      "\d0BBE",  # TAMIL SYLLABLE VAA
      "\d0BB5",  # TAMIL SYLLABLE VI
      "\d0BBF",  # TAMIL SYLLABLE VI
      "\d0BB5",  # TAMIL SYLLABLE VII
      "\d0BC0",  # TAMIL SYLLABLE VII
      "\d0BB5",  # TAMIL SYLLABLE VU
      "\d0BC1",  # TAMIL SYLLABLE VU
      "\d0BB5",  # TAMIL SYLLABLE VUU
      "\d0BC2",  # TAMIL SYLLABLE VUU
      "\d0BB5",  # TAMIL SYLLABLE VE
      "\d0BC6",  # TAMIL SYLLABLE VE
      "\d0BB5",  # TAMIL SYLLABLE VEE
      "\d0BC7",  # TAMIL SYLLABLE VEE
      "\d0BB5",  # TAMIL SYLLABLE VAI
      "\d0BC8",  # TAMIL SYLLABLE VAI
      "\d0BB5",  # TAMIL SYLLABLE VO
      "\d0BCA",  # TAMIL SYLLABLE VO
      "\d0BB5",  # TAMIL SYLLABLE VOO
      "\d0BCB",  # TAMIL SYLLABLE VOO
      "\d0BB5",  # TAMIL SYLLABLE VAU
      "\d0BCC",  # TAMIL SYLLABLE VAU
      "\d0BB4",  # TAMIL SYLLABLE LLLAA
      "\d0BBE",  # TAMIL SYLLABLE LLLAA
      "\d0BB4",  # TAMIL SYLLABLE LLLI
      "\d0BBF",  # TAMIL SYLLABLE LLLI
      "\d0BB4",  # TAMIL SYLLABLE LLLII
      "\d0BC0",  # TAMIL SYLLABLE LLLII
      "\d0BB4",  # TAMIL SYLLABLE LLLU
      "\d0BC1",  # TAMIL SYLLABLE LLLU
      "\d0BB4",  # TAMIL SYLLABLE LLLUU
      "\d0BC2",  # TAMIL SYLLABLE LLLUU
      "\d0BB4",  # TAMIL SYLLABLE LLLE
      "\d0BC6",  # TAMIL SYLLABLE LLLE
      "\d0BB4",  # TAMIL SYLLABLE LLLEE
      "\d0BC7",  # TAMIL SYLLABLE LLLEE
      "\d0BB4",  # TAMIL SYLLABLE LLLAI
      "\d0BC8",  # TAMIL SYLLABLE LLLAI
      "\d0BB4",  # TAMIL SYLLABLE LLLO
      "\d0BCA",  # TAMIL SYLLABLE LLLO
      "\d0BB4",  # TAMIL SYLLABLE LLLOO
      "\d0BCB",  # TAMIL SYLLABLE LLLOO
      "\d0BB4",  # TAMIL SYLLABLE LLLAU
      "\d0BCC",  # TAMIL SYLLABLE LLLAU
      "\d0BB3",  # TAMIL SYLLABLE LLAA
      "\d0BBE",  # TAMIL SYLLABLE LLAA
      "\d0BB3",  # TAMIL SYLLABLE LLI
      "\d0BBF",  # TAMIL SYLLABLE LLI
      "\d0BB3",  # TAMIL SYLLABLE LLII
      "\d0BC0",  # TAMIL SYLLABLE LLII
      "\d0BB3",  # TAMIL SYLLABLE LLU
      "\d0BC1",  # TAMIL SYLLABLE LLU
      "\d0BB3",  # TAMIL SYLLABLE LLUU
      "\d0BC2",  # TAMIL SYLLABLE LLUU
      "\d0BB3",  # TAMIL SYLLABLE LLE
      "\d0BC6",  # TAMIL SYLLABLE LLE
      "\d0BB3",  # TAMIL SYLLABLE LLEE
      "\d0BC7",  # TAMIL SYLLABLE LLEE
      "\d0BB3",  # TAMIL SYLLABLE LLAI
      "\d0BC8",  # TAMIL SYLLABLE LLAI
      "\d0BB3",  # TAMIL SYLLABLE LLO
      "\d0BCA",  # TAMIL SYLLABLE LLO
      "\d0BB3",  # TAMIL SYLLABLE LLOO
      "\d0BCB",  # TAMIL SYLLABLE LLOO
      "\d0BB3",  # TAMIL SYLLABLE LLAU
      "\d0BCC",  # TAMIL SYLLABLE LLAU
      "\d0BB1",  # TAMIL SYLLABLE RRAA
      "\d0BBE",  # TAMIL SYLLABLE RRAA
      "\d0BB1",  # TAMIL SYLLABLE RRI
      "\d0BBF",  # TAMIL SYLLABLE RRI
      "\d0BB1",  # TAMIL SYLLABLE RRII
      "\d0BC0",  # TAMIL SYLLABLE RRII
      "\d0BB1",  # TAMIL SYLLABLE RRU
      "\d0BC1",  # TAMIL SYLLABLE RRU
      "\d0BB1",  # TAMIL SYLLABLE RRUU
      "\d0BC2",  # TAMIL SYLLABLE RRUU
      "\d0BB1",  # TAMIL SYLLABLE RRE
      "\d0BC6",  # TAMIL SYLLABLE RRE
      "\d0BB1",  # TAMIL SYLLABLE RREE
      "\d0BC7",  # TAMIL SYLLABLE RREE
      "\d0BB1",  # TAMIL SYLLABLE RRAI
      "\d0BC8",  # TAMIL SYLLABLE RRAI
      "\d0BB1",  # TAMIL SYLLABLE RRO
      "\d0BCA",  # TAMIL SYLLABLE RRO
      "\d0BB1",  # TAMIL SYLLABLE RROO
      "\d0BCB",  # TAMIL SYLLABLE RROO
      "\d0BB1",  # TAMIL SYLLABLE RRAU
      "\d0BCC",  # TAMIL SYLLABLE RRAU
      "\d0BA9",  # TAMIL SYLLABLE NNNAA
      "\d0BBE",  # TAMIL SYLLABLE NNNAA
      "\d0BA9",  # TAMIL SYLLABLE NNNI
      "\d0BBF",  # TAMIL SYLLABLE NNNI
      "\d0BA9",  # TAMIL SYLLABLE NNNII
      "\d0BC0",  # TAMIL SYLLABLE NNNII
      "\d0BA9",  # TAMIL SYLLABLE NNNU
      "\d0BC1",  # TAMIL SYLLABLE NNNU
      "\d0BA9",  # TAMIL SYLLABLE NNNUU
      "\d0BC2",  # TAMIL SYLLABLE NNNUU
      "\d0BA9",  # TAMIL SYLLABLE NNNE
      "\d0BC6",  # TAMIL SYLLABLE NNNE
      "\d0BA9",  # TAMIL SYLLABLE NNNEE
      "\d0BC7",  # TAMIL SYLLABLE NNNEE
      "\d0BA9",  # TAMIL SYLLABLE NNNAI
      "\d0BC8",  # TAMIL SYLLABLE NNNAI
      "\d0BA9",  # TAMIL SYLLABLE NNNO
      "\d0BCA",  # TAMIL SYLLABLE NNNO
      "\d0BA9",  # TAMIL SYLLABLE NNNOO
      "\d0BCB",  # TAMIL SYLLABLE NNNOO
      "\d0BA9",  # TAMIL SYLLABLE NNNAU
      "\d0BCC",  # TAMIL SYLLABLE NNNAU
      "\d0B9C",  # TAMIL SYLLABLE JAA
      "\d0BBE",  # TAMIL SYLLABLE JAA
      "\d0B9C",  # TAMIL SYLLABLE JI
      "\d0BBF",  # TAMIL SYLLABLE JI
      "\d0B9C",  # TAMIL SYLLABLE JII
      "\d0BC0",  # TAMIL SYLLABLE JII
      "\d0B9C",  # TAMIL SYLLABLE JU
      "\d0BC1",  # TAMIL SYLLABLE JU
      "\d0B9C",  # TAMIL SYLLABLE JUU
      "\d0BC2",  # TAMIL SYLLABLE JUU
      "\d0B9C",  # TAMIL SYLLABLE JE
      "\d0BC6",  # TAMIL SYLLABLE JE
      "\d0B9C",  # TAMIL SYLLABLE JEE
      "\d0BC7",  # TAMIL SYLLABLE JEE
      "\d0B9C",  # TAMIL SYLLABLE JAI
      "\d0BC8",  # TAMIL SYLLABLE JAI
      "\d0B9C",  # TAMIL SYLLABLE JO
      "\d0BCA",  # TAMIL SYLLABLE JO
      "\d0B9C",  # TAMIL SYLLABLE JOO
      "\d0BCB",  # TAMIL SYLLABLE JOO
      "\d0B9C",  # TAMIL SYLLABLE JAU
      "\d0BCC",  # TAMIL SYLLABLE JAU
      "\d0BB6",  # TAMIL SYLLABLE SHAA
      "\d0BBE",  # TAMIL SYLLABLE SHAA
      "\d0BB6",  # TAMIL SYLLABLE SHI
      "\d0BBF",  # TAMIL SYLLABLE SHI
      "\d0BB6",  # TAMIL SYLLABLE SHII
      "\d0BC0",  # TAMIL SYLLABLE SHII
      "\d0BB6",  # TAMIL SYLLABLE SHU
      "\d0BC1",  # TAMIL SYLLABLE SHU
      "\d0BB6",  # TAMIL SYLLABLE SHUU
      "\d0BC2",  # TAMIL SYLLABLE SHUU
      "\d0BB6",  # TAMIL SYLLABLE SHE
      "\d0BC6",  # TAMIL SYLLABLE SHE
      "\d0BB6",  # TAMIL SYLLABLE SHEE
      "\d0BC7",  # TAMIL SYLLABLE SHEE
      "\d0BB6",  # TAMIL SYLLABLE SHAI
      "\d0BC8",  # TAMIL SYLLABLE SHAI
      "\d0BB6",  # TAMIL SYLLABLE SHO
      "\d0BCA",  # TAMIL SYLLABLE SHO
      "\d0BB6",  # TAMIL SYLLABLE SHOO
      "\d0BCB",  # TAMIL SYLLABLE SHOO
      "\d0BB6",  # TAMIL SYLLABLE SHAU
      "\d0BCC",  # TAMIL SYLLABLE SHAU
      "\d0BB7",  # TAMIL SYLLABLE SSAA
      "\d0BBE",  # TAMIL SYLLABLE SSAA
      "\d0BB7",  # TAMIL SYLLABLE SSI
      "\d0BBF",  # TAMIL SYLLABLE SSI
      "\d0BB7",  # TAMIL SYLLABLE SSII
      "\d0BC0",  # TAMIL SYLLABLE SSII
      "\d0BB7",  # TAMIL SYLLABLE SSU
      "\d0BC1",  # TAMIL SYLLABLE SSU
      "\d0BB7",  # TAMIL SYLLABLE SSUU
      "\d0BC2",  # TAMIL SYLLABLE SSUU
      "\d0BB7",  # TAMIL SYLLABLE SSE
      "\d0BC6",  # TAMIL SYLLABLE SSE
      "\d0BB7",  # TAMIL SYLLABLE SSEE
      "\d0BC7",  # TAMIL SYLLABLE SSEE
      "\d0BB7",  # TAMIL SYLLABLE SSAI
      "\d0BC8",  # TAMIL SYLLABLE SSAI
      "\d0BB7",  # TAMIL SYLLABLE SSO
      "\d0BCA",  # TAMIL SYLLABLE SSO
      "\d0BB7",  # TAMIL SYLLABLE SSOO
      "\d0BCB",  # TAMIL SYLLABLE SSOO
      "\d0BB7",  # TAMIL SYLLABLE SSAU
      "\d0BCC",  # TAMIL SYLLABLE SSAU
      "\d0BB8",  # TAMIL SYLLABLE SAA
      "\d0BBE",  # TAMIL SYLLABLE SAA
      "\d0BB8",  # TAMIL SYLLABLE SI
      "\d0BBF",  # TAMIL SYLLABLE SI
      "\d0BB8",  # TAMIL SYLLABLE SII
      "\d0BC0",  # TAMIL SYLLABLE SII
      "\d0BB8",  # TAMIL SYLLABLE SU
      "\d0BC1",  # TAMIL SYLLABLE SU
      "\d0BB8",  # TAMIL SYLLABLE SUU
      "\d0BC2",  # TAMIL SYLLABLE SUU
      "\d0BB8",  # TAMIL SYLLABLE SE
      "\d0BC6",  # TAMIL SYLLABLE SE
      "\d0BB8",  # TAMIL SYLLABLE SEE
      "\d0BC7",  # TAMIL SYLLABLE SEE
      "\d0BB8",  # TAMIL SYLLABLE SAI
      "\d0BC8",  # TAMIL SYLLABLE SAI
      "\d0BB8",  # TAMIL SYLLABLE SO
      "\d0BCA",  # TAMIL SYLLABLE SO
      "\d0BB8",  # TAMIL SYLLABLE SOO
      "\d0BCB",  # TAMIL SYLLABLE SOO
      "\d0BB8",  # TAMIL SYLLABLE SAU
      "\d0BCC",  # TAMIL SYLLABLE SAU
      "\d0BB9",  # TAMIL SYLLABLE HAA
      "\d0BBE",  # TAMIL SYLLABLE HAA
      "\d0BB9",  # TAMIL SYLLABLE HI
      "\d0BBF",  # TAMIL SYLLABLE HI
      "\d0BB9",  # TAMIL SYLLABLE HII
      "\d0BC0",  # TAMIL SYLLABLE HII
      "\d0BB9",  # TAMIL SYLLABLE HU
      "\d0BC1",  # TAMIL SYLLABLE HU
      "\d0BB9",  # TAMIL SYLLABLE HUU
      "\d0BC2",  # TAMIL SYLLABLE HUU
      "\d0BB9",  # TAMIL SYLLABLE HE
      "\d0BC6",  # TAMIL SYLLABLE HE
      "\d0BB9",  # TAMIL SYLLABLE HEE
      "\d0BC7",  # TAMIL SYLLABLE HEE
      "\d0BB9",  # TAMIL SYLLABLE HAI
      "\d0BC8",  # TAMIL SYLLABLE HAI
      "\d0BB9",  # TAMIL SYLLABLE HO
      "\d0BCA",  # TAMIL SYLLABLE HO
      "\d0BB9",  # TAMIL SYLLABLE HOO
      "\d0BCB",  # TAMIL SYLLABLE HOO
      "\d0BB9",  # TAMIL SYLLABLE HAU
      "\d0BCC",  # TAMIL SYLLABLE HAU
      "\d0B95",  # TAMIL SYLLABLE KSSA
      "\d0BCD",  # TAMIL SYLLABLE KSSA
      "\d0BB7",  # TAMIL SYLLABLE KSSA
      "\d0B95",  # TAMIL SYLLABLE KSSAA
      "\d0BCD",  # TAMIL SYLLABLE KSSAA
      "\d0BB7",  # TAMIL SYLLABLE KSSAA
      "\d0BBE",  # TAMIL SYLLABLE KSSAA
      "\d0B95",  # TAMIL SYLLABLE KSSI
      "\d0BCD",  # TAMIL SYLLABLE KSSI
      "\d0BB7",  # TAMIL SYLLABLE KSSI
      "\d0BBF",  # TAMIL SYLLABLE KSSI
      "\d0B95",  # TAMIL SYLLABLE KSSII
      "\d0BCD",  # TAMIL SYLLABLE KSSII
      "\d0BB7",  # TAMIL SYLLABLE KSSII
      "\d0BC0",  # TAMIL SYLLABLE KSSII
      "\d0B95",  # TAMIL SYLLABLE KSSU
      "\d0BCD",  # TAMIL SYLLABLE KSSU
      "\d0BB7",  # TAMIL SYLLABLE KSSU
      "\d0BC1",  # TAMIL SYLLABLE KSSU
      "\d0B95",  # TAMIL SYLLABLE KSSUU
      "\d0BCD",  # TAMIL SYLLABLE KSSUU
      "\d0BB7",  # TAMIL SYLLABLE KSSUU
      "\d0BC2",  # TAMIL SYLLABLE KSSUU
      "\d0B95",  # TAMIL SYLLABLE KSSE
      "\d0BCD",  # TAMIL SYLLABLE KSSE
      "\d0BB7",  # TAMIL SYLLABLE KSSE
      "\d0BC6",  # TAMIL SYLLABLE KSSE
      "\d0B95",  # TAMIL SYLLABLE KSSEE
      "\d0BCD",  # TAMIL SYLLABLE KSSEE
      "\d0BB7",  # TAMIL SYLLABLE KSSEE
      "\d0BC7",  # TAMIL SYLLABLE KSSEE
      "\d0B95",  # TAMIL SYLLABLE KSSAI
      "\d0BCD",  # TAMIL SYLLABLE KSSAI
      "\d0BB7",  # TAMIL SYLLABLE KSSAI
      "\d0BC8",  # TAMIL SYLLABLE KSSAI
      "\d0B95",  # TAMIL SYLLABLE KSSO
      "\d0BCD",  # TAMIL SYLLABLE KSSO
      "\d0BB7",  # TAMIL SYLLABLE KSSO
      "\d0BCA",  # TAMIL SYLLABLE KSSO
      "\d0B95",  # TAMIL SYLLABLE KSSOO
      "\d0BCD",  # TAMIL SYLLABLE KSSOO
      "\d0BB7",  # TAMIL SYLLABLE KSSOO
      "\d0BCB",  # TAMIL SYLLABLE KSSOO
      "\d0B95",  # TAMIL SYLLABLE KSSAU
      "\d0BCD",  # TAMIL SYLLABLE KSSAU
      "\d0BB7",  # TAMIL SYLLABLE KSSAU
      "\d0BCC",  # TAMIL SYLLABLE KSSAU
      "\d0BB6",  # TAMIL SYLLABLE SHRII
      "\d0BCD",  # TAMIL SYLLABLE SHRII
      "\d0BB0",  # TAMIL SYLLABLE SHRII
      "\d0BC0",  # TAMIL SYLLABLE SHRII
      "\d0DCA",  # SINHALA CONSONANT SIGN YANSAYA
      "\d200D",  # SINHALA CONSONANT SIGN YANSAYA
      "\d0DBA",  # SINHALA CONSONANT SIGN YANSAYA
      "\d0DCA",  # SINHALA CONSONANT SIGN RAKAARAANSAYA
      "\d200D",  # SINHALA CONSONANT SIGN RAKAARAANSAYA
      "\d0DBB",  # SINHALA CONSONANT SIGN RAKAARAANSAYA
      "\d0DBB",  # SINHALA CONSONANT SIGN REPAYA
      "\d0DCA",  # SINHALA CONSONANT SIGN REPAYA
      "\d200D",  # SINHALA CONSONANT SIGN REPAYA
      "\d10E3",  # GEORGIAN LETTER U-BRJGU
      "\d0302",  # GEORGIAN LETTER U-BRJGU
      "\d17D2",  # KHMER CONSONANT SIGN COENG KA
      "\d1780",  # KHMER CONSONANT SIGN COENG KA
      "\d17D2",  # KHMER CONSONANT SIGN COENG KHA
      "\d1781",  # KHMER CONSONANT SIGN COENG KHA
      "\d17D2",  # KHMER CONSONANT SIGN COENG KO
      "\d1782",  # KHMER CONSONANT SIGN COENG KO
      "\d17D2",  # KHMER CONSONANT SIGN COENG KHO
      "\d1783",  # KHMER CONSONANT SIGN COENG KHO
      "\d17D2",  # KHMER CONSONANT SIGN COENG NGO
      "\d1784",  # KHMER CONSONANT SIGN COENG NGO
      "\d17D2",  # KHMER CONSONANT SIGN COENG CA
      "\d1785",  # KHMER CONSONANT SIGN COENG CA
      "\d17D2",  # KHMER CONSONANT SIGN COENG CHA
      "\d1786",  # KHMER CONSONANT SIGN COENG CHA
      "\d17D2",  # KHMER CONSONANT SIGN COENG CO
      "\d1787",  # KHMER CONSONANT SIGN COENG CO
      "\d17D2",  # KHMER CONSONANT SIGN COENG CHO
      "\d1788",  # KHMER CONSONANT SIGN COENG CHO
      "\d17D2",  # KHMER CONSONANT SIGN COENG NYO
      "\d1789",  # KHMER CONSONANT SIGN COENG NYO
      "\d17D2",  # KHMER CONSONANT SIGN COENG DA
      "\d178A",  # KHMER CONSONANT SIGN COENG DA
      "\d17D2",  # KHMER CONSONANT SIGN COENG TTHA
      "\d178B",  # KHMER CONSONANT SIGN COENG TTHA
      "\d17D2",  # KHMER CONSONANT SIGN COENG DO
      "\d178C",  # KHMER CONSONANT SIGN COENG DO
      "\d17D2",  # KHMER CONSONANT SIGN COENG TTHO
      "\d178D",  # KHMER CONSONANT SIGN COENG TTHO
      "\d17D2",  # KHMER CONSONANT SIGN COENG NA
      "\d178E",  # KHMER CONSONANT SIGN COENG NA
      "\d17D2",  # KHMER CONSONANT SIGN COENG TA
      "\d178F",  # KHMER CONSONANT SIGN COENG TA
      "\d17D2",  # KHMER CONSONANT SIGN COENG THA
      "\d1790",  # KHMER CONSONANT SIGN COENG THA
      "\d17D2",  # KHMER CONSONANT SIGN COENG TO
      "\d1791",  # KHMER CONSONANT SIGN COENG TO
      "\d17D2",  # KHMER CONSONANT SIGN COENG THO
      "\d1792",  # KHMER CONSONANT SIGN COENG THO
      "\d17D2",  # KHMER CONSONANT SIGN COENG NO
      "\d1793",  # KHMER CONSONANT SIGN COENG NO
      "\d17D2",  # KHMER CONSONANT SIGN COENG BA
      "\d1794",  # KHMER CONSONANT SIGN COENG BA
      "\d17D2",  # KHMER CONSONANT SIGN COENG PHA
      "\d1795",  # KHMER CONSONANT SIGN COENG PHA
      "\d17D2",  # KHMER CONSONANT SIGN COENG PO
      "\d1796",  # KHMER CONSONANT SIGN COENG PO
      "\d17D2",  # KHMER CONSONANT SIGN COENG PHO
      "\d1797",  # KHMER CONSONANT SIGN COENG PHO
      "\d17D2",  # KHMER CONSONANT SIGN COENG MO
      "\d1798",  # KHMER CONSONANT SIGN COENG MO
      "\d17D2",  # KHMER CONSONANT SIGN COENG YO
      "\d1799",  # KHMER CONSONANT SIGN COENG YO
      "\d17D2",  # KHMER CONSONANT SIGN COENG RO
      "\d179A",  # KHMER CONSONANT SIGN COENG RO
      "\d17D2",  # KHMER CONSONANT SIGN COENG LO
      "\d179B",  # KHMER CONSONANT SIGN COENG LO
      "\d17D2",  # KHMER CONSONANT SIGN COENG VO
      "\d179C",  # KHMER CONSONANT SIGN COENG VO
      "\d17D2",  # KHMER CONSONANT SIGN COENG SHA
      "\d179D",  # KHMER CONSONANT SIGN COENG SHA
      "\d17D2",  # KHMER CONSONANT SIGN COENG SSA
      "\d179E",  # KHMER CONSONANT SIGN COENG SSA
      "\d17D2",  # KHMER CONSONANT SIGN COENG SA
      "\d179F",  # KHMER CONSONANT SIGN COENG SA
      "\d17D2",  # KHMER CONSONANT SIGN COENG HA
      "\d17A0",  # KHMER CONSONANT SIGN COENG HA
      "\d17D2",  # KHMER CONSONANT SIGN COENG LA
      "\d17A1",  # KHMER CONSONANT SIGN COENG LA
      "\d17D2",  # KHMER VOWEL SIGN COENG QA
      "\d17A2",  # KHMER VOWEL SIGN COENG QA
      "\d17D2",  # KHMER INDEPENDENT VOWEL SIGN COENG QU
      "\d17A7",  # KHMER INDEPENDENT VOWEL SIGN COENG QU
      "\d17D2",  # KHMER INDEPENDENT VOWEL SIGN COENG RY
      "\d17AB",  # KHMER INDEPENDENT VOWEL SIGN COENG RY
      "\d17D2",  # KHMER INDEPENDENT VOWEL SIGN COENG RYY
      "\d17AC",  # KHMER INDEPENDENT VOWEL SIGN COENG RYY
      "\d17D2",  # KHMER INDEPENDENT VOWEL SIGN COENG QE
      "\d17AF",  # KHMER INDEPENDENT VOWEL SIGN COENG QE
      "\d17BB",  # KHMER VOWEL SIGN OM
      "\d17C6",  # KHMER VOWEL SIGN OM
      "\d17B6",  # KHMER VOWEL SIGN AAM
      "\d17C6",  # KHMER VOWEL SIGN AAM
      "\d304B",  # HIRAGANA LETTER BIDAKUON NGA
      "\d309A",  # HIRAGANA LETTER BIDAKUON NGA
      "\d304D",  # HIRAGANA LETTER BIDAKUON NGI
      "\d309A",  # HIRAGANA LETTER BIDAKUON NGI
      "\d304F",  # HIRAGANA LETTER BIDAKUON NGU
      "\d309A",  # HIRAGANA LETTER BIDAKUON NGU
      "\d3051",  # HIRAGANA LETTER BIDAKUON NGE
      "\d309A",  # HIRAGANA LETTER BIDAKUON NGE
      "\d3053",  # HIRAGANA LETTER BIDAKUON NGO
      "\d309A",  # HIRAGANA LETTER BIDAKUON NGO
      "\d30AB",  # KATAKANA LETTER BIDAKUON NGA
      "\d309A",  # KATAKANA LETTER BIDAKUON NGA
      "\d30AD",  # KATAKANA LETTER BIDAKUON NGI
      "\d309A",  # KATAKANA LETTER BIDAKUON NGI
      "\d30AF",  # KATAKANA LETTER BIDAKUON NGU
      "\d309A",  # KATAKANA LETTER BIDAKUON NGU
      "\d30B1",  # KATAKANA LETTER BIDAKUON NGE
      "\d309A",  # KATAKANA LETTER BIDAKUON NGE
      "\d30B3",  # KATAKANA LETTER BIDAKUON NGO
      "\d309A",  # KATAKANA LETTER BIDAKUON NGO
      "\d30BB",  # KATAKANA LETTER AINU CE
      "\d309A",  # KATAKANA LETTER AINU CE
      "\d30C4",  # KATAKANA LETTER AINU TU
      "\d309A",  # KATAKANA LETTER AINU TU
      "\d30C8",  # KATAKANA LETTER AINU TO
      "\d309A",  # KATAKANA LETTER AINU TO
      "\d31F7",  # KATAKANA LETTER AINU P
      "\d309A",  # KATAKANA LETTER AINU P
      "\d02E5",  # MODIFIER LETTER EXTRA-HIGH EXTRA-LOW CONTOUR TONE BAR
      "\d02E9",  # MODIFIER LETTER EXTRA-HIGH EXTRA-LOW CONTOUR TONE BAR
      "\d02E9",  # MODIFIER LETTER EXTRA-LOW EXTRA-HIGH CONTOUR TONE BAR
      "\d02E5",  # MODIFIER LETTER EXTRA-LOW EXTRA-HIGH CONTOUR TONE BAR
    ]
    test_data.each do |string|
      assert @validator.valid_encoding?(string), "U10_NamedSequences: #{string}"
      assert string.force_encoding("UTF-8").valid_encoding?, "U10_NamedSequences: #{string}" if @vercheck
    end
  end

end
